### ISSUE TITLE
"static" keyword breaks doxygen parameterization

### ISSUE THREAD

**Issue by clozach** [20Tauri/DoxyDoxygen#10]
Steps to reproduce:
- Install "DoxyDoxygen (evolution)" + restart Sublime Text
- Use DoxyDoxygen on these two functions:
  
  static func test1() {}
  func test2() {}

Results:

```
/**
 * 
 */
static func test1() {}

/**
 * @brief      { function_description }
 */
func test2() {}
```

Note the missing `@brief` for `test1()`

**Comment by 20Tauri** [comment]
Thank you for reporting.
Swift is currently only supported by DoxyDoxygen (evolution) (v0.13.7+) branches and really now (see [history](https://github.com/20Tauri/DoxyDoxygen/releases) for details)

"static" problem have just be fixed (test-suite updated) and I will release a new version soon.
If you have others problems simply give me the incorrecly documented examples

**Comment by 20Tauri** [comment]
0.13.8 has just been released and will solve this issue (and many others on Swift support)
Still not perfect, but better
