### ISSUE TITLE
How to silence auto-update notifications

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#100]
DoxyDoxyen seems to auto-update and display a 'Package Control Messages' tab very often when first starting up Sublime Text.

Of course I have nothing against frequent updates, but at this point I see its messages several orders of magnitude more often than any other package that I use.

Would it be possible to squash these notifications, either permanently or for a certain period of time? I

**Comment by 20Tauri** [comment]
Each version of DoxyDoxygen come with a changelog.
So, each time Package Control upgrade DoxyDoxygen, PackageControl will display this changelog.
Upgrade frequency may be [configured globally in Package Control](https://packagecontrol.io/docs/settings).  You can also disable auto upgrade for this package.

Another approach: if you use the [Evolution version](https://packagecontrol.io/packages/DoxyDoxygen%20(evolution)) (the version with most frequent upgrade), you can move to [the regular version](https://packagecontrol.io/packages/DoxyDoxygen).
