### ISSUE TITLE
uppercase letter 'L'

### ISSUE THREAD

**Issue by ghost** [20Tauri/DoxyDoxygen#102]
Only in the comment section that is generated with doxy-doxygen the letter l
appears in uppercase 'L'. Any idea on how to fix it?

**Comment by 20Tauri** [comment]
Sounds like the expected behaviour according default autofill rules.
Please check, the `autofill_rules` and `autofill_rules_default` settings
If you don't solve your problem yourself, please provide a full example (entity to document, result, expected)
