### ISSUE TITLE
Can't update DoxyDoxygen

### ISSUE THREAD

**Issue by smfelsher** [20Tauri/DoxyDoxygen#103]
I am receiving an error dialog when I open Sublime indicating that it cannot upgrade DoxyDoxygen. Here is the snippet from the console.

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://github.com/20Tauri/DoxyDoxygen/releases/download/0.63.3/ST3_DoxyDoxygen.sublime-package.
error: Package Control

Unable to download DoxyDoxygen. Please view the console for more details.
```

Seems to be a certificate issue with GitHub? Is there something I need to do on my side?

**Comment by 20Tauri** [comment]
Thank you for reporting,

Unfortunately I have no solution

Manually using the same URI: https://github.com/20Tauri/DoxyDoxygen/releases/download/0.63.3/ST3_DoxyDoxygen.sublime-package , I have the same issue using tls 1.1 or above (try security.tls.version.max;1 in firefox for example)

To solve this, PackageControl has to use TLS 1.2
The best is probably to report it to wbond (packagecontrol)

**Comment by smfelsher** [comment]
Yes, it appears that there is an issue with Package Control. Here is a reference to the ticket: https://github.com/wbond/package_control/issues/1334. For now, it seems the fix is to temporarily set `curl` as the download agent and not use `urllib`. 

Anyone stumbling across this ticket **please check the aforementioned Package Control ticket for the latest status**

**Comment by 20Tauri** [comment]
As this tip don't work for Windows user, due to a bug in Package Control (check for `curl` instead of `curl.exe`). I Strongly advice to XP, Windows 2008, Window Vista user to apply [KB4019276](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4019276) if they encounter any problem.

**Comment by jasjuang** [comment]
@20Tauri Thanks for the heads up. After adding the below to preferences->Package settings->Package control->Settings - User solves it for me.

```
"downloader_precedence":
{
	"linux":
	[
		"curl",
		"urllib",
		"wget"
	],
}
```
