### ISSUE TITLE
Generatate doc block with /** + tab

### ISSUE THREAD

**Issue by predragnikolic** [20Tauri/DoxyDoxygen#104]
Currently if I want to add a doc comment I need eather to press `Alt+Q`or to press `/** + Enter`, which is fine. 
But it would be nice to have an option for `/** + tab` to trigger the doc block as well.

**Comment by jfcherng** [comment]
Just add the following to your keybindings.
```javascript
{
    "keys": ["tab"],
    "command": "doxy_enter",
    "context": [
        { "key": "auto_complete_visible", "operator": "equal",  "operand": false,       "match_all": true },
        { "key": "selector",              "operator": "equal",  "operand": "comment, string.quoted.double.block.cython, string.quoted.single.block.cython, string.quoted.double.block.python, string.quoted.single.block.python, string.quoted.docstring.multi.python", "match_all": true }
    ]
},
```
---

So, generally, how do we get the above key binding for a plugin?

1. `` Ctrl+` `` to open the console and type `Sublime.log_commands(True)`
1. Trigger the commands that you are interested. In this case, it's `/** + enter`.
1. You would find that the console shows `doxy_enter`. This is the command that we are interested in.
1. Open the keybindings of Doxydoxygen and find `doxy_enter`.
1. Copy and paste it to your own keybindings and modify the `keys` from `enter` to `tab`.

**Comment by 20Tauri** [comment]
Thank you Jack for this detailed response
I really like when user reply another user

**Comment by predragnikolic** [comment]
Thank you :-)
