### ISSUE TITLE
[C++] unable to work with function with dll macros and pointer return type

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#105]
Please see below minimal code,

```
class Sample
{
 public:

  WINDOWS_DLL camera *getConnection();
};
```

When I click the function and type alt+Q nothing happens, however the below two scenario works

```
class Sample
{
 public:

  WINDOWS_DLL camera getConnection();
};
```

```
class Sample
{
 public:

  camera *getConnection();
};
```

So it seems like a problem of the combination of dll macros and pointer return type. Would be great to see this fixed!

**Comment by jasjuang** [comment]
Another thing is if it's a reference it also breaks it, see

```
class Sample
{
 public:

  WINDOWS_DLL camera &getConnection();
};
```

**Comment by jasjuang** [comment]
@20Tauri Just want to make sure you see this. I find it weird that you replied to #106 but not this one. Thanks!

**Comment by 20Tauri** [comment]
0.65.0 has just been released (evolution branch). This version is focused on C++ and introduce a way to declare macros (this will solve some ambiguities)

**Comment by jasjuang** [comment]
@20Tauri Thanks. I can confirm that after declaring the DLL macros in the doxydoxygen settings this problem goes away. 

However, in the company I am working on, the actual DLL macro looks like `WINDOWS_<company name>_<repo name>_DLL`, adding all possible combinations into the doxydoxygen settings is a little bit hard to enforce company wide. 

Is it possible to make something like the below work?

```
{

    "c_macros": [
        "WINDOWS_*_DLL="
    ]

}
```

Something like `*` in bash.

**Comment by 20Tauri** [comment]
Undocumentated, but reg exp are supported, try something like "WINDOWS_[A-Z0-9_]*_DLL="

**Comment by jasjuang** [comment]
@20Tauri Phenomenal! I tried it and it works for me.

**Comment by jasjuang** [comment]
@20Tauri It seems like recent updates break this. "WINDOWS_[A-Z0-9_]*_DLL=" doesn't seem to work anymore, but if I explicitly spell it out and not use regex it works. Did you accidentally disable regex support for `c_macros`?

**Comment by 20Tauri** [comment]
Unfortunatly it is the new expected behavior [0.72.0 release notes](https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.72.0)...
When macros with arguments was introduced "(" has become ambiguous...

I will reintroduce partially the previous behavior in 0.73.0 (names can be regexp with neither "(", nor "="). Use regexp in this case still unadvised.

**Comment by jasjuang** [comment]
I got the 0.73.0 update and everything seems to be working like usual again. Thanks!
