### ISSUE TITLE
[C++] unable to work with function return type with nested STL and line breaks

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#106]
Please see the below minimal code to reproduce the problem,

```
class Sample
{
 public:
 	
  std::map<aaaaaaaaaaaaaaaaaaaa, std::vector<bbbbbbbbbbbbbbbbbbbbbbbbbbbb>>
  myfunc();
};
```

If I click the function and do alt+Q nothing happens. However, the below scenarios works

```
class Sample
{
 public:
 	
  std::map<a, std::vector<b>> myfunc();
};
```
```
class Sample
{
 public:
 	
  std::map<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbb>>
  myfunc();
};
```

It seems like it's the combination of line break and nested STL that breaks it. We are using clang-format with a hard 80 character per line limit so it will be hard to alter that. One of the external libraries we are using have these long nested STL arguments, we could typedef it to try to workaround it but then the code becomes a bit confusing afterwards. It would be great if doxydoxygen can handle this scenario!

**Comment by 20Tauri** [comment]
Thank, your analysis is the right
 To make the difference between ">>" and ">" in my tokenizer I use a regexp and I've hardcode a space, so linefeed, tab cause problems.

This will be fix in the next release that will be released today in evolution branch)

**Comment by jasjuang** [comment]
@20Tauri I am getting an error when trying to update. Tried it on two computers and both gives the same error. Can you take a look?

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://github.com/20Tauri/DoxyDoxygen/releases/download/0.64.0/ST3_DoxyDoxygen.sublime-package.
error: Package Control

Unable to download DoxyDoxygen (evolution). Please view the console for more details.
```

**Comment by 20Tauri** [comment]
It's a bug in package control, more info [here](https://github.com/20Tauri/DoxyDoxygen/issues/103)
