### ISSUE TITLE
[PHP]  Alt+Q makes PHPUnit annotations into the same line

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#108]
Using Alt+Q on a method that has been well-documented with PHPUnit annotations.

I am using ST 3164.

Reference: [PHPUnit Annotations](https://phpunit.de/manual/6.5/en/appendixes.annotations.html)

![image](https://user-images.githubusercontent.com/6594915/39065058-2e3b5d34-4503-11e8-8dc0-fe58a37212db.png)

```php
<?php

use PHPUnit\Framework\TestCase;

/**
 * @coversNothing
 */
class MyTest extends TestCase
{
    /**
     * Test example.
     *
     * @covers Example
     * @dataProvider firstTestcaseProvider
     * @dataProvider secondTestcaseProvider
     *
     * @param array $input    The input
     * @param array $expected The expected
     */
    public function testExample(array $input, array $expected): void
    {
        // ...
    }
}
```

**Comment by 20Tauri** [comment]
PhpUnit tags are not currently supported but you can add a DoxyDoxygen module to detect them

**Comment by jfcherng** [comment]
@20Tauri Do we have documents about adding a DoxyDoxygen module? Find nothing using the term `module`. http://20tauri.free.fr/DoxyDoxygen/v2/search.php?q=module&check_keywords=yes&area=default

**Comment by 20Tauri** [comment]
Documentation may be found here: http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php?highlight=plug#add-your-own-doc-style

**Comment by 20Tauri** [comment]
Even if not initially planned, I've added PhpUnit support to the lastest release.
As if you have defined your own doc-style, you will also gain snippet for all the annotation

**Comment by jfcherng** [comment]
@20Tauri Confirmed working. Thanks for your work!
