### ISSUE TITLE
Requesting ability to specify different column width for wrapping

### ISSUE THREAD

**Issue by FHTheron** [20Tauri/DoxyDoxygen#112]
I like to re-wrap comment blocks within 77 character widths, regardless of the margin position. For example, with WrapLinesPlus a keybinding can add an argument to specify a width. It would be nice if the same idea could apply to `doxy_update_comments` here which could then make it behave as a simple re-wrap command in general comment blocks.

**Comment by 20Tauri** [comment]
Thanks for suggestion.
A first ruler at 77 can be a temporaly solution (the first ruler is not always the lowest one)

I will probably add a specific parameter in settings (I don't see any use case where this settings have to be different from one command to another)

**Comment by 20Tauri** [comment]
0.66.0 (currently deployed in evolution branch) introduce a new parameter to specify different column width for wrapping

**Comment by 20Tauri** [comment]
Now also released in regular version 0.66.1
