### ISSUE TITLE
How to prevent reformat of markdown code blocks

### ISSUE THREAD

**Issue by cheoAlejo** [20Tauri/DoxyDoxygen#113]
I have the following documentation with a brief example of how to use de method:

```php
    /**
     * Trae el valor de una celda que es de tipo fecha, y retorna un objeto PHP
     * de la clase DateTime.
     *
     * @see    getCell()
     * @link http://php.net/manual/en/book.datetime.php DateTime PHP
     *
     * @param  string|array  $pCoordinate Coordenadas de la celda, ver
     *                                    `getCell()`
     *
     * @return \DateTime     Retorna el objeto PHP de la clase DateTime.
     * 
     * #### Example
     * 
     * ```php
     * $fechaObj = $sheet->getCellDatetime('A1');
     * // Imprimir año / mes / día
     * echo $fechaObj->format('Y / m / d');
     * ```
     */
    public function getCellDatetime($pCoordinate = 'A1')
```

The problem is that when we execute the update command, everything get reformatted, including the markdown code block of the example:

```php
    /**
     * Trae el valor de una celda que es de tipo fecha, y retorna un objeto PHP
     * de la clase DateTime.
     *
     * @see    getCell()
     * @link   http://php.net/manual/en/book.datetime.php DateTime PHP
     *
     * @param  string|array  $pCoordinate Coordenadas de la celda, ver
     *                                    `getCell()`
     *
     * @return \DateTime     Retorna el objeto PHP de la clase DateTime.
     *
     * #### Example
     *
     * ```php $fechaObj = $sheet->getCellDatetime('A1'); // Imprimir año / mes /
     * día echo $fechaObj->format('Y / m / d'); ```
     */
    public function getCellDatetime($pCoordinate = 'A1')
```

**Comment by 20Tauri** [comment]
Using doxygen, simply try `@code` `@endcode`...
Please refer to https://github.com/20Tauri/DoxyDoxygen/issues/94

**Comment by cheoAlejo** [comment]
Thanks for the answer. Still can't get it to work.

Before:
![image](https://user-images.githubusercontent.com/10518807/41729579-2e99218c-753f-11e8-90ed-b9bd25dabd06.png)

After any of these commands: `doxy_update_comments(reparse=True) or doxy_update_comments(reparse=False)`:
![image](https://user-images.githubusercontent.com/10518807/41729607-4330bc4a-753f-11e8-98ac-3b4cbf3763f5.png)

**Comment by 20Tauri** [comment]
`@code` and `@endcode` are doxygen commands.
And setting default use PhpDocumentor as default doc-style for php.
You you probably want to use it.
Markdown are the right way to document code block using PhpDocumentor.
So, I have made the change

In version 0.67.0 (evolution branch), I have added the support of markdown code block.
Your first example will work now fine out of the box

**Comment by cheoAlejo** [comment]
Understood. Great! I'll look forward to the 0.67 version.
