### ISSUE TITLE
Specific profiles for specific projects

### ISSUE THREAD

**Issue by slifin** [20Tauri/DoxyDoxygen#115]
Apologies if I've missed this in the documentation but how do I have a different profile per project?
I'd like to use Drupal doc styles on one project and Symfony on another

**Comment by 20Tauri** [comment]
No, it's not possible to have a different profile per project.
This question is not DoxyDoxygen specific and should be treated in Sublime Text (or a dedicated plugin).

**Comment by slifin** [comment]
It is possible for plugins to support this, I actively use this with SublimeLinter to have different lint settings per project see here:
http://www.sublimelinter.com/en/stable/settings.html#project

**Comment by 20Tauri** [comment]
I mean that is not possible on the current version.
According me, it's better to implement this globally than locally in each plugin... This will increase consistence. For example, the SublimeLinter Project Settings Priority Stack mismatchs the SublimeText priority stack (even if take sense in their case).

But I have decided to implement it in the next DoxyDoxygen version. Specification will be::

To define `Project Settings`, you can edit the `.sublimetext-project` file and add a `DoxyDoxygen` section in the `settings` section. All settings can be overload here. Project Settings overload the default User Settings.

```
    "settings":
    {
        "DoxyDoxygen": {
            "merge_matching_ratio": 0.5,
        }
    },
```

**Comment by 20Tauri** [comment]
Now released in both Regular and Evolution versions
