### ISSUE TITLE
Comment at the end of a line

### ISSUE THREAD

**Issue by gj1118** [20Tauri/DoxyDoxygen#116]
Hi , 
Is there a way I can use DoxyDoxygen to insert a comment at the end of the line ? For example , I want to insert a comment where the current cursor is in the url below.
https://cl.ly/3L3s190V0m2W

Can you please help me out with this ?

Thanks

**Comment by 20Tauri** [comment]
Hi,

There's no shortcut to generate a comment at the end of line. The need looks specific and doxydoxygen will have low added value in this case. So, adding a new shortcut as default may be counter prodictive.

The easiest is probably to write your own shortcut and use a snippet (save it with the .sublime-snippet extension)

```xml
<snippet>
    <content><![CDATA[
${TM_COMMENT_START} ${1:comment} ${TM_COMMENT_END}
]]></content>
</snippet>
```

Regards

**Comment by gj1118** [comment]
I created the snippet and saved it as  `endofline.sulime-snippet` . Now whenever I try to run it , I get the following error 

https://cl.ly/1u2B2y3a1i1U

Please suggest

Thanks
Gagan

**Comment by 20Tauri** [comment]
My example was containing an extra and useless variable... Previous comment is now fixed

**Comment by 20Tauri** [comment]
Hope now it's work on your side.
