### ISSUE TITLE
Better support for joining lines

### ISSUE THREAD

**Issue by rchl** [20Tauri/DoxyDoxygen#117]
I use ctrl/cmd+j to join lines within the comment block to reformat multiline comment block into one line. So this:

```
/**
 * @param {Object}
 */
```
into this:
```
/** @param {Object} */
```
The simplest way to do it would be to press cmd+j twice on first line but for that to work seamlessly, the package would need to remove extra `*` characters on joining. And also be smart about handling white space (leave one space before block end).

DocBlock has partial support for that - it worked apart from joining the end of the block.

**Comment by 20Tauri** [comment]
<kbd>Ctrl</kbd>+<kbd>J</kbd> was not catched by this plugin unlike DocBlockr...

Adding this feature is not really difficult, but I'm not sure that is the best way to solve your problem...
Why ? When you will update your comment, you will need to join manually again

The DoxyDoxygen approach is different. You define your `block_layout_default` and `preferred_comments_styles` once then on creation / update, the plugin will make your command match this layout.

**Comment by rchl** [comment]
Good point but maybe for this case it's not likely that comment will be updated. I imagine you would only want to join comment into one line when it has one @ "property" like @type or @return. In that case it's not really likely to update it (at least using automatic function).

**Comment by 20Tauri** [comment]
In the following example, I have explained how to remove unwanted linebreak.
But, my remark is global. It can be the main comment, it can be a list of items... In this case (like with `@ "property"` tag), the `preferred_line_length` will split lines...

In fact, I don't see good use of this feature... but if several users request it, it can be implemented (this feature break no rule, but the workflow)
