### ISSUE TITLE
Insert doc comment on /**[enter]*/

### ISSUE THREAD

**Issue by rchl** [20Tauri/DoxyDoxygen#118]
I'm quite used to adding documentation comment by pressing super+alt+/ to insert block comment, then adding one `*` and pressing enter. This doesn't trigger documentation creation in this plugin (but does in competition :)).

So:
1. super+alt+/ -- `/*|*/`
2. press `*` -- `/**|*/`
3. Press enter.

**Comment by 20Tauri** [comment]
You are probably new on SublimeText.
This doesn't really related to this plugin but you can add this custom key binding to get the expected job.

```
	{ "keys": ["super+alt+/"], "command": "toggle_comment", "args": { "block": true } },
```

**Comment by rchl** [comment]
I think you might have misundestood.

The shortcut you posted seems just like a standard shortcut to create a block comment. I'm already using it in my point '1'. My point was that pressing enter while having `/**|*/` would expand to create the doxygen comment automatically.

(I've created a couple of Sublime packages and contributed to many so I wouldn't call myself a Sublime newbie. :))

**Comment by 20Tauri** [comment]
You are right.

When you press <kbd>enter</kbd> on a closed comment, the command `doxy_enter` will continue the comment. The case of an empty comment is not considered as a special case

Entering `/**` (without `*/`), then press <kbd>enter</kbd> will do the expected job.

I you realy want this workflow... To detect this case, "content" test on "following_text", "preceding_text", can be used. Then call the command `doxy_update_comments`

**Comment by rchl** [comment]
I'll add it locally but my point was to consider including it by default as it should be an extra way of creating documentation that would add to robustness.

For reference, this works for me:

```
  { "keys": ["enter"], "command": "doxy_update_comments", "context":
    [
      { "key": "selector", "operator": "equal",  "operand": "comment", "match_all": true },
      { "key": "preceding_text", "operator": "regex_contains", "operand": "\\s*\/\\*\\*\\s*", "match_all": true },
      { "key": "following_text", "operator": "regex_contains", "operand": "\\*\/\\s*", "match_all": true },
    ]
  },
```

**Comment by 20Tauri** [comment]
Thanks,

Will probably not be included in the default package (I dislike the workflow)
But may be included in documentation.

Regards,
