### ISSUE TITLE
[Mac] Shortcut for switching comment style conflicts with system action

### ISSUE THREAD

**Issue by rchl** [20Tauri/DoxyDoxygen#119]
Readme suggests that switching comment style is possible with Super+Shift+Alt+Q on Mac. That shortcut triggers logout on Mac. The actual command for logging out is Super+Shift+Q but it triggers with Alt pressed too.

**Comment by 20Tauri** [comment]
Thanks

I have no Mac to test it...

- The global shortcut seem to be disabled in "System Preferences > Keyboard > Shortcuts > App Shortcuts"
- You can change the comment style from to palette "DoxyDoxygen: Update Command With User-Selected Style"
- You can also make your own keybinding ("Preference: DoxyDoxygen Keys-binding")

But you are right, this shortcut is probably not the best choice...
If Mac users have any suggestions they are welcome.

**Comment by rchl** [comment]
I don't see the logout shortcut listed in "System Preferences > Keyboard > Shortcuts > App Shortcuts" or anywhere else in that dialog so I'm not sure you can actually disable or enable it. Not in user friendly way at least.

**Comment by 20Tauri** [comment]
On OS/X, Super+Shift+Alt+Q will be changed to Super+Shift+Alt+K in next release (0.70.1)
Unperfect (because hard to memorize) but will prevent to log out if you follow the user manual.
I also wonder if 'K' is not a better choice on OS/X than 'Q' on this system

**Comment by rchl** [comment]
The documentation still mentions the annoying (and potentially dangerous) shortcut for Mac:

![Screenshot 2020-07-27 at 21 16 17](https://user-images.githubusercontent.com/153197/88582092-6c3a2d80-d04e-11ea-8b62-4ce5cfbbdd99.png)

http://20tauri.free.fr/DoxyDoxygen/v2/page_usage.php#create-a-documentation-block

**Comment by 20Tauri** [comment]
Thank you,

The right shortcut is <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>K</kbd>.
Will be fixed in the next documentation generation
