### ISSUE TITLE
Minors issues to fix

### ISSUE THREAD

**Issue by sidati** [20Tauri/DoxyDoxygen#12]
Hello,
first of all thank you very mush for this great plugin, secondly when i type :
<code>/***</code> and hit <code>enter</code> the plugin works great but when i type the function description and hit <code>Enter</code> the cursor go just beside the <code>*[cursor]</code> it must gone to new line type <code>*</code> and space to be like this <code>*[space][cursor]</code>.

and please fix the issue when i type <code>@</code> i still need ti click <code>Ctrl+Space</code> to display auto-compilations.
- [x] Sublime text 3
- [x] Windows 7
- [x] PHP Language

Thank again :+1: ,
Sidati

**Comment by 20Tauri** [comment]
Hello,

Thank you for reporting.

Good suggestion. In next release, on comment continuation, I will preserve indentation AND add a single space if the previous line is empty.

The reported 'issue' is just sublime text configuration. There's no default trigger. Adding following line in your settings will solve it.

``` javascript
"auto_complete_triggers": [ {"selector": "comment", "characters": "@"} ],
```

It's non trivial. I will look for a way to define trigger programmaticly (or in plugin settings)

Regards,

PS: I don't understand your title... Have you detect a lack with PHP parser ?

**Comment by sidati** [comment]
Thanks for reply, and sorry for the missed-up title,
by the way i start waiting for the new updates :+1:

**Comment by 20Tauri** [comment]
0.15.0 is released !
The comment continuation problem has been fixed
I haven't take time to look for a way to define triggers automatically... But I keep your remark in mind

**Comment by sidati** [comment]
Just get the update on my ST3 (DoxyDoxygen 0.15.0),
for the auto-trigger i think : just adding it as notice/info in the readme/doc will be enough till you figure it out.
<code>
"auto_complete_triggers": [ {"selector": "comment", "characters": "@"} ],
</code>
Really appreciate your effort, Thank you very mush

Best,
Sidati
