### ISSUE TITLE
Custom command being renamed

### ISSUE THREAD

**Issue by smfelsher** [20Tauri/DoxyDoxygen#120]
I have defined a custom Doxygen command, `@satisfy`. When I press `Alt+q` in my comment block with the custom command, the custom command is renamed to the `@see` command

`@satisfy{6}`  ---> `@see     tisfy{6}`

What configuration setting is causing this to happen?

**Comment by 20Tauri** [comment]
The plugin detect `@sa` tag en replace it with `@see`. To preserve `@sa`, you can you
```json
    "preserve_aliases": true,
```

I can also prevent command detection when the command is a letter and the next character is a letter (and will probably do in the next release). But once again, this will not help for you use case.

To define new tag, you can chain `DocStyle` (first style is the default one). Example:
```json
        {
            "languages":  [ "c++", "c" ],
            "parsers":    [ "LanguageCpp", "**<Your DocStyle Here>**" ],
            "doc_styles": [ "Doxygen" ]
        },
```

To define your own docstyle, please refer follow this example https://github.com/20Tauri/DoxyDoxygen_contrib_HeaderDoc.

Sound a little tricky for your badic need... I have planned to define command in a json format to allow to extend the plugin more easily for trivial case...

**Comment by smfelsher** [comment]
I set `   "preserve_aliases": true` in my `Doxy.Sublime-settings -- User` file, restarted Sublime, but still, the substitution occurs. Did I misunderstand your directions?

**Comment by 20Tauri** [comment]
On version 0.68.0, setting `preserve_aliases` to `true` will produce `@sa tisfy{6}` (with a space)

On version 0.68.1, `@satisfy{6}` is recognize a a regular word. No subsitution bug will be included in the previous tag.

If you defined your new keywork (using plugin), you can have a whole/correct reformating for your custom tag.

**Comment by smfelsher** [comment]
I don't think I want to implement my own DocStyle, so I'll wait for 0.68.1.

**Comment by 20Tauri** [comment]
0.68.1 is out since one day... You can get it on "DoxyDoxygen (evolution)" branch.
But, the change is not exactly what you will expect it will only remove subsitution.

I agree you, should be easier to add/extend tags... For exmaple tags can be overload/define in an editable JSON file. Something like that:

```
"commands_list" : [
    {
        "name": "@const",
        "args:" '\t{ description_of_the_variable }",
        "help": "Documents a constant within an enumeration"
        "aliases": [ "@constant" ]
    },
    // ....
]
```
