### ISSUE TITLE
[C++] Constructor cannot be recognized by doxydoxygen if there is no line break in between public

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#124]
Here is the minimal code to recreate the problem

```
class Sample
{
 public:
  Sample();
};
```

alt + Q on the constructors does nothing, however if I add a line break like

```
class Sample
{
 public:

  Sample();
};
```

it will function like usual. This is a minor annoyance but will still be nice to see this fixed!

**Comment by 20Tauri** [comment]
This is not constructor specific. Entity detection will be improved in next release.
