### ISSUE TITLE
[C++] DLL macros causes doxydoxygen to not recognize contructor

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#125]
Please see below minimal code

```
class Sample
{
 public:

  WINDOWS_DLL Sample();

};
```

if the cursor is at the constructor and I type alt+q it will become

```
class Sample
{
 public:

  /**
   * @brief      { function_description }
   *
   * @return     { description_of_the_return_value }
   */
  WINDOWS_DLL Sample();

};
```

but I am expecting

```
class Sample
{
 public:

  /**
   * @brief      Constructs the object.
   */
  WINDOWS_DLL Sample();

};
```

would be nice to see this fixed! On a side note, destructors are not affected by DLL macros.

```
class Sample
{
 public:

  /**
   * @brief      Destroys the object.
   */
  WINDOWS_DLL ~Sample();

};
```

alt+q yields expected results.

**Comment by 20Tauri** [comment]
Please refer to your previous repert https://github.com/20Tauri/DoxyDoxygen/issues/95.

The plugin cannot guess own macros will be expanded, by you can configure `c_macros` to help it.
