### ISSUE TITLE
Alt-Q indentation inconsistency and list preservation

### ISSUE THREAD

**Issue by drbartling** [20Tauri/DoxyDoxygen#130]
```
/**
 * @brief      Initializes the battery pack (DPM)
 *
 *             1. Identifies the battery pack
 *             2. Checks validity
 *             3. If not USB, updates dpm data and writes back to battery
 *
 * @note       This is a macro in order to avoid changing the built binaries
 *             during refactoring.
 *
 * @todo       When testing infrastructure is more robust, refactor into a function.
 */
#define dpm_init()                                                             \
```

Becomes
```
/**
 * @brief      Initializes the battery pack (DPM)
 *
 *             1. Identifies the battery pack 2. Checks validity 3. If not USB,
 *             updates dpm data and writes back to battery
 *
 * @note       This is a macro in order to avoid changing the built binaries
 *             during refactoring.
 *
 * @todo When testing infrastructure is more robust, refactor into a function.
 *
 * @return     { description_of_the_return_value }
 */
#define dpm_init()                                                             \
```

**Comment by 20Tauri** [comment]
The right way to do it is `-#`
Please refer to the [Doxygen Manual](https://www.star.bnl.gov/public/comp/sofi/doxygen/lists.html) for further information

**Comment by drbartling** [comment]
> The right way to do it is `-#`
> Please refer to the [Doxygen Manual](https://www.star.bnl.gov/public/comp/sofi/doxygen/lists.html) for further information

Okay, and the indentation of the @todo?

**Comment by drbartling** [comment]
Also, since [Doxygen supports](http://www.doxygen.nl/manual/markdown.html#md_lists) markdown style lists, would you be willing to support that, since it makes the docs in the code more directly readable?

**Comment by 20Tauri** [comment]
Following changes will be applied in the 0.70.2 (just released)

   - Add: Doxygen Mardown list support (https://github.com/20Tauri/DoxyDoxygen/issues/130)
   - Fix: Doxygen `@todo` doesn't work properly with `doxygen_paragraph_prefix` (https://github.com/20Tauri/DoxyDoxygen/issues/130)

Will be available in both channel (evolution & regular)

**Comment by drbartling** [comment]
Thanks :)
