### ISSUE TITLE
[question] doxygen snippet autocomplete

### ISSUE THREAD

**Issue by arcturus140** [20Tauri/DoxyDoxygen#134]
is it possible to use `\` style comments instead of `@` style comments with autocomplete?

The former is easier to type but with default setting autocomplete only triggers using the latter.

**Comment by 20Tauri** [comment]
Not sure to understand... The setting is
```json
    "doxygen_command_prefix": "\\",
```

And, it will (shoudl ?) work with both `completion` (<kbd>ctrl</kbd>+<kbd>space</kbd>) and full comment generation (<kbd>alt</kbd>+<kbd>q</kbd>)

If you have any problem, please give, at least:
   - the exact sublime text version used
   - the exact doxydoxygen version used (if not the lastest, please update)
   - a context (code example, settings, keys pressed, result expected and obtain)

The reporting agent, included in the plugin, may help (but not mandatory)

**Comment by arcturus140** [comment]
I wasn't aware of this setting - it works

thank you
