### ISSUE TITLE
PHP variadic function wrong variable name

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#135]
# Problem

[Variadic function](https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.variadics) is introduced in PHP 5.6. Here's a simple example.

```php
function variadicFunction(...$args): array
{
    return $args;
}
```

The generated PHPDoc looks like the following.
```php
/**
 * { function_description }
 *
 * @param ... $args The arguments
 *
 * @return ...|array ( description_of_the_return_value )
 */
function variadicFunction(...$args): array
{
    return $args;
}
```

It looks like the `...` is treated as the variable type of `$arg` but actually it is not and no type is declared here.

# Expected Result

```php
/**
 * { function_description }
 *
 * @param <type> ...$args The arguments
 *
 * @return array ( description_of_the_return_value )
 */
function variadicFunction(...$args): array
{
    return $args;
}
```

Just a note. Here, the `<type>` is the type of the element of `$args` rather than `$args` itself.

Reference: https://github.com/phpDocumentor/fig-standards/issues/121#issuecomment-429202033

# Another Problem that May Be Related

Say, now I have my doc edited manually as the following.

```php
/**
 * This is a variadic function.
 *
 * @param mixed ...$args The arguments
 *
 * @return array
 */
function variadicFunction(...$args): array
{
    return $args;
}
```

Now I press <kbd>Alt+Q</kbd>(`doxy_comment_nearest_entity`). The doc becomes

```php
/**
 * This is a variadic function.
 *
 * @param mixed $args The arguments
 *
 * @return array
 */
function variadicFunction(...$args): array
{
    return $args;
}
```

The `...` is removed by plugin.

**Comment by 20Tauri** [comment]
Thanks for reporting,

As the current generated comment match no recommendation, I have implemented your suggestion ("old" PhpStorm syntax)... 

But the syntax seems tools dependant (discussed [here on StackOverflow](https://stackoverflow.com/questions/14513356/phpdoc-documenting-a-function-with-a-variable-number-of-arguments) )

PhpDoc documentation defines:

```php
/**
 * @param mixed $args,... The arguments
 */
```

This option seem to be a better choice...
What is your opinion about this syntax ?
Is it compliant with your editor ?

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/61256990-a0bfac00-a7a1-11e9-8622-aabc63f4184e.png)


Yes, it's okay in my use case as well. Either way, it's better than the current one. Thanks!

**Comment by 20Tauri** [comment]
Thanks

0.71.0 is now released on the evolution branch
Will be pushed in the regular branch next week

**Comment by jfcherng** [comment]
Works for me. Thanks.

**Comment by jfcherng** [comment]
It looks like my static analyzer (phan) doesn't like this syntax. I have to check with the author.

**Comment by jfcherng** [comment]
I check some most famous PHP static analysis tools.

- phpstan: https://github.com/phpstan/phpstan/issues/1530#issuecomment-431654951
- phan (the one I use curretly): https://github.com/phan/phan/issues/2982#issuecomment-512082382
- psalm: https://github.com/vimeo/psalm/issues/148#issuecomment-296687779

All of them are using `@param <type> ...$args` as the doc of a variadic funciton.
Since PHPStorm also accepts that form, I suggest we use it as the default one for best compatibility.
Or, hopefully make it configurable as an user preference.

**Comment by 20Tauri** [comment]
Thanks again,

0.71.1 is now released. On comment update the "...$args" notation will be applied

**Comment by jfcherng** [comment]
LGTM. Thanks!
