### ISSUE TITLE
Documentation block creation fails with namespaces

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#14]
DoxyDoxygen fails to parse functions inside namespaces, when using the 'Comment Nearest Entity' Command.

For example, given this trivial project: https://gist.github.com/JohannesMP/5fe9bcdd8e53fe667028, where namespace `Foo` contains class `Bar` which has a constructor and a function `GetDerp`.

If I want to create a documentation block for the implementation of the class constructor by placing my cursor on <a href=https://gist.github.com/JohannesMP/5fe9bcdd8e53fe667028#file-bar-cpp-L5>line 5 of bar.cpp</a> and use `Super`+`Alt`+`Q` (as a mac user) it says that it was unable to find a function:
![screenshot_2015-09-22_20 56 07](https://cloud.githubusercontent.com/assets/662874/10037548/939dceb4-616c-11e5-99fc-7bac3e6848ac.png)

However if I use autocomplete when typing `/**` then the function is completed:
![doxygen6](https://cloud.githubusercontent.com/assets/662874/10039272/157fefee-6185-11e5-8e8b-ae4ca567740d.gif)

At this point if I place my cursor inside the block the command seems to complete, stating "Field 1 of N" where N increases each time I invoke the command.

However I still don't have the convenience of being able to reliably update the code block that now exists. 

For example, If I add a parameter, click into the comment block and do `Super`+`Alt`+`Q` it will add the corresponding @param entry:
![screenshot_2015-09-22_23 57 10](https://cloud.githubusercontent.com/assets/662874/10039330/aab74670-6185-11e5-943c-991581fa0212.png)

But if I then remove the parameter and try to update the same way it will remove the description, but not the `@param` entry.
![screenshot_2015-09-22_23 58 04](https://cloud.githubusercontent.com/assets/662874/10039344/c8fdaed0-6185-11e5-92c9-5dbab0620a8c.png)

---

Settings used here were default c++/Doxygen: https://gist.github.com/JohannesMP/a3dbcd5c942d2a7cff6e

**Comment by 20Tauri** [comment]
I use SublimeText scopes to locate function. So "Comment Nearest Entity" may have syntax issue
I have tested your example on both SublimeText 2.0.2 and SublimeText 3 (3084)
Both work fine for me.

To help me to solve this problem, please at 3 cursors.
- the first one, on the function name
- the second one, on the namespace name
- the last one, on the location where you have pressed <kbd>ALT</kbd>+<kbd>Q</kbd>

Then in contextual menu, select "Doxygen Report -> Anomaly report".
This will generate a report like this.

```
#### Edited text
##### Cursor 1
source.c++ meta.namespace-block.c++ 
"""
#include "bar.hpp"

namespace F
"""
__CURSOR__
"""
oo
{

  Bar::Bar(int derp) : derp_(derp)
  {}

  int Bar::GetDerp()
  {
    return derp_;
  }
}
"""

##### Cursor 2
source.c++ meta.namespace-block.c++ 
"""
#include "bar.hpp"

namespace Foo
{

"""
__CURSOR__
"""

  Bar::Bar(int derp) : derp_(derp)
  {}

  int Bar::GetDerp()
  {
    return derp_;
  }
}
"""

##### Cursor 3
source.c++ meta.namespace-block.c++ meta.function.constructor.c++ entity.name.function.c++ 
"""
#include "bar.hpp"

namespace Foo
{

  Bar::B
"""
__CURSOR__
"""
ar(int derp) : derp_(derp)
  {}

  int Bar::GetDerp()
  {
    return derp_;
  }
}
"""
```

Then, we will compare our scope. Mine are
- source.c++ meta.namespace-block.c++ 
- source.c++ meta.namespace-block.c++ 
- source.c++ meta.namespace-block.c++ meta.function.constructor.c++ entity.name.function.c++ 

"entity.name.function" will probably miss.

Once generated, to send the report
The easiest way to send it is to use the contextual menu and select  ">>> send report <<<"

**Comment by JohannesMP** [comment]
I think this issue might be as a result of me using <a href=https://packagecontrol.io/packages/C%20Improved>`C Improved`</a> as my syntax for c++. (it claims to cover C/C++/Objective-C).

As a result my scopes for the corresponding cursors are (I just used <a href=https://packagecontrol.io/packages/ScopeAlways>ScopeAlways</a> to display my current scopes in the status bar) 
- source.c
- source.c meta.block.c
- source.c meta.block.c meta.function-call.c support.function.any-method.c

Changing the syntax of my page from `C Improved` to `C++` fixed the issue.

Would it be possible to make changes that would allow cpp files set to `C Improved` to still work with DoxyDoxygen?

(Using Sublime Text 3 - 3083)

**Comment by 20Tauri** [comment]
It's strange to use a C syntax for C++...
You also probably lost sublime text function "goto symbol"

In this case Syntax "think" that you are in a body... and "symbol()" is a function call

**Comment by JohannesMP** [comment]
To quote their documentation "Other languages derived from C (like C++ and Objective C) don't need their syntaxes to be changed to something special: they usually extend source.c under the hood, which is now provided by C Improved syntax."

But you're probably right. I'll try switching back to the default c++ syntax.

**Comment by 20Tauri** [comment]
In next relase, I will add the current "syntax" name in the integrated report.
Will help analysis
