### ISSUE TITLE
Don't introduce trailing white space

### ISSUE THREAD

**Issue by rchl** [20Tauri/DoxyDoxygen#141]
Not sure if the problem is specific to Python but I've noticed it there lately.

Pressed shortcut to generate documentation for a function and got this:
![Screenshot 2020-05-14 at 21 57 04](https://user-images.githubusercontent.com/153197/81979910-03860c00-962e-11ea-9807-142d0587cd50.png)

Trailing spaces should not be added when adding documentation.
Version 0.76.2

**Comment by 20Tauri** [comment]
This occurs when there's blank line...
It's not python specific but docstrings are the most common case.
Spaces are not directly generated by the plugin, but the plugin use "insert_snippet". And spaces are generated by "insert_snippet.

To reproduce just using "insert_snippet
   - Press <kbd>Tab</kbd> to leave the first column,
   - Then, from the console enter `view.run_command("insert_snippet", {"contents": "\n-----------\n\n--------------\n"})`
   - See the result... you have reproduced the problem

If someone know how to solve this,..

As, usually, on save whitespaces are removed, this will hide the problem.

**Comment by rchl** [comment]
Do you have the range of created block? If yes then you can just kill trailing spaces with a regex.
```py
re.sub('^[ \t]+$', text, '', count=0, flags=re.MULTILINE)
```

**Comment by 20Tauri** [comment]
Please try my example. The empty line introduced by "\n\n" sequence will produce the problem... and there's no whitespace in "\n\n".

**Comment by rchl** [comment]
Yes, I can reproduce. I was just trying to find a solution outside of having ST API fixed. But I don't know your code so I can only guess what is available to you.

**Comment by 20Tauri** [comment]
A way to fix this problem is to insert the newline before insert the snippet.

This is implemented in 0.76.3 (evolution channel only).
This version also include the 2 others problems you have discovered.

Thanks again for your reporting

**Comment by rchl** [comment]
Looks good now. Thanks :)
