### ISSUE TITLE
Sublime Text 4 JSX Support

### ISSUE THREAD

**Issue by nickhstr** [20Tauri/DoxyDoxygen#145]
Using Sublime Text 4, build 4077, on macOS 10.15.5.
All DoxyDoxygen commands and keyboard shortcuts do not work for the new built-in JSX syntax (scope of `source.jsx`).

**Comment by jfcherng** [comment]
Just to add more potentially useful information here.
![image](https://user-images.githubusercontent.com/6594915/87351828-97bc1300-c58c-11ea-9265-7f17010f5a57.png)

As of ST 4075, they introduced the JSX syntax via a new syntax definition capability: `extends`.
See https://github.com/sublimehq/Packages/blob/40ec1f2f9b56fb55d739e17ecd003cc9e8c9b096/JavaScript/JSX.sublime-syntax#L7
It's something like inheriting from a parent syntax.

**Comment by 20Tauri** [comment]
Thanks for reporting,

The problem seem to be in Packages/JavaScript/Comments.tmPreferences.
If you try `view.meta_info("shellVariables", 0)` in the console for this syntax you will NOT see that TM_COMMENT_START defined (unlike JavaScript syntax).
This will cause other troubles: Comment toggling probably doesn't work.

To fix it, in JavaScript.sublime-package
Replace: 	`<string>source.js, source.json</string>`
With: 	`<string>source.js, source.jsx, source.json</string>`

Let me know if it solve all problems

In the next release, JSX comment introducers will be forced. This will make DoxyDoxygen works with JSX even without syntax update

**Comment by 20Tauri** [comment]
Thanks for the fix in `sublimehq/Packages`.
I have just released a 0.76.4 version (evolution brancgh) that fix the problem even with the buggy `JavaScript.sublime-package`
