### ISSUE TITLE
Allow @brief on first line of a block

### ISSUE THREAD

**Issue by everclear72216** [20Tauri/DoxyDoxygen#147]
I'm obsessed with saving vertical screen space. I would like to configure a block layout that puts \@_brief on the same line as the block start.

    /** Brief Description
     *  \param name Parameter Description
     */
This format also requires that the commands are shifted 1 column to the right. Furthermore I would like the parameter names to be column aligned but parameter descriptions shall only be separated by a space from the parameter names. I fiddled with the configuration hoping to find some undocumented features to no avail. Am I just not getting it or am I actually requesting a feature?

**Comment by 20Tauri** [comment]
Use both `preferred_comments_styles` and `block_layout`.

The example following example may help.

```json
    "preferred_comments_styles": [
        [
            ["/**", "", ""],
            " *  "
        ],
    ],

    "block_layout": {
         "Doxygen": [
             {
                 "tags": [
                     "@_brief",
                     "@param",
                     "@tparam",
                     "@return",
                     "@throws",
                     ""
                 ],
             }
         ],
    },
```

**Comment by everclear72216** [comment]
Perfect. Works.
