### ISSUE TITLE
How to set 2 spaces as indentation within C-style doxygen blocks?

### ISSUE THREAD

**Issue by rwols** [20Tauri/DoxyDoxygen#148]
At my current company we use this kind of doxygen style:

```
/**
 *  Some brief explanation (note the 2 spaces of indentation)
 *
 *  @param arg1 Some arg1
 *  @param arg2 some arg2
 *  @return What it returns
 */
```
How would I go about creating a template for this style?

**Comment by 20Tauri** [comment]
Simply use `" *  "` instead of `" * "`.
Already explained in https://github.com/20Tauri/DoxyDoxygen/issues/147

Have I miss something ?

**Comment by rwols** [comment]
Apologies, I didn't look at that issue.
