### ISSUE TITLE
Is `INI.tmLanguage` needed?

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#150]
Today I just found that there are 3 `INI` syntaxes in my command palette.

One from my own, one from [EditorConfig](https://github.com/sindresorhus/editorconfig-sublime) and one from here.

- Mine is just taken from https://github.com/jwortmann/ini-syntax/blob/master/INI.sublime-syntax
- The EditorConfig's will be fixed by the [PR](https://github.com/sindresorhus/editorconfig-sublime/pull/90) if it gets merged.
- Not sure why I need a (non-hidden) `INI` syntax definition in this package?

**Comment by 20Tauri** [comment]
Doxyfile configuration files are INI and are not catched by INI package.
As an INI syntax is needed, why not use it for all INI like files ? 

List of extensions that INI support and not DoxyDoxygen
  - .buckconfig
  - .flowconfig
  - .hgrc (mercural)

Example of extensions that DoxyDoxygen support and not INI
   - reg
   - buildozer.spec (kiwy)
   - .editorconfig

... and `hidden_file_extensions` requiere ST 4075 to work.

Cons:
- look less modular

Pro:
- easier to integrate
- no need of external package (and DoxyDoxygen still work with ST 2)

Why do you prefer INI syntax from INI package over the included one in DoxyDoxygen ?

**Comment by jfcherng** [comment]
NVM. Comes up with a solution locally.

Since you have to support ST 2, I guess it's hard to change here.
