### ISSUE TITLE
Doc generation when using arrow functions in TypeScript

### ISSUE THREAD

**Issue by dvcrn** [20Tauri/DoxyDoxygen#151]
For example:

<img width="811" alt="Screen Shot 2021-01-04 at 18 58 02" src="https://user-images.githubusercontent.com/688326/103523483-3f245d80-4ebf-11eb-8d2e-5a44033a82c8.png">

The plugin isn't able to get the function signature when using arrow functions. It just inserts the generic @return placeholder

I'm guessing this is more an issue with jsdoc, but any way around this?

**Comment by 20Tauri** [comment]
TypeScript support uses a generic parser.
In this example, the Javascript parser gives a "better" result ...
Adding support for ":" in the javascript parser and switching to the JavaScript parser for TypeScript syntax will improve the result.
Will be considered in a future version

Here the current result with Javascript parser
```javascript
/**
 * Adds a global click handler.
 *
 * @param      {<type>}  emailFieldElements:Element[]  The email field elements element
 * @return     {number}  { description_of_the_return_value }
 */
const addGlobalClickHandler = (emailFieldElements: Element[]) => {
    return 1;
}
```

**Comment by 20Tauri** [comment]
0.78.0 (DoxyDoxygen Evolution) is now out.
This version has a better TypeScript support (including arrow functions and generic functions)

**Comment by dvcrn** [comment]
Oh very nice, thanks! Let me give that a go
