### ISSUE TITLE
Feature Request: Numpy docstring style

### ISSUE THREAD

**Issue by LDAP** [20Tauri/DoxyDoxygen#152]
Many projects use the numpy docstring style as specified here:

https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard

Is there any chance to get this added?

**Comment by 20Tauri** [comment]
DocStyles can be extended but, there is no plan to add a NumPyDoc build-in support in a near futur.
So, you can try to implement it or you can use a Python specific plugin like SublimeAutoDocstring.

**Comment by LDAP** [comment]
Alright. Maybe I find some time in the future, I did already notice your contrib-template.

(Btw. I tried to contact you via your website form regarding licensing)

**Comment by 20Tauri** [comment]
Thank you for reporting (nothing was received from the contact page).
The contact page seems to silently fail.
I temporarily removed it (and put a direct contact email instead)
