### ISSUE TITLE
Use both Doxygen syntax and C++ syntax at the same time.

### ISSUE THREAD

**Issue by zuoya213** [20Tauri/DoxyDoxygen#154]
Is there any way to use both the Doxygen syntax and C++ syntax at the same time?

![image](https://user-images.githubusercontent.com/74475332/113955926-a6b5b600-97ea-11eb-85a8-a632909afe0a.png)

I need to switch between them to view the doc strings with syntax highlighting and it takes a lot of time.

**Comment by 20Tauri** [comment]
Unfortunately, not easily.
Sublimetext allows [mixing syntax files](https://forum.sublimetext.com/t/different-syntax-modes-in-a-same-document/21304), but you will need to create your own "C++" syntax to do this.
And remember that `doc_styles` is a setting... There's no warranty that all C++ users will use Doxygen (QT Doc is an alternative for example). So, it cannot be directly integrated into the main plugin.
Another approach is to highlight commands dynamically (using sublime_plugin.EventListener). This approach independent of `doc_styles` but it requires managing the refresh delay and CPU consumption.  It has been experimented with poor results and no plan to integrate it into production yet.

**Comment by zuoya213** [comment]
I've tried merging the two syntax files together, however it only shows the C++ syntax. Do you have a way to do it?

**Comment by 20Tauri** [comment]
The previously given link explain how to do the job.
[SublimeText syntaxes](https://www.sublimetext.com/docs/syntax.html) allow to include external file.
Remember that, for compatibility reason, Doxydoxygen syntax files use the deprecated TextMate format (may be a problem with some approachs).
As syntaxes are part of SublimeText, you probably will have a better support on the SublimeText forum directly.
