### ISSUE TITLE
[C++] Doxydoxygen is unable to parse inline latex equations

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#156]
For the below doxygen comments that includes an inline latex equation

```
/**
 * @brief      Runs \f$Ax=b\f$
 */
void solve();
```

pressing alt + q will cause it to become

```
/**
 * @brief      Runs
 *             @f$Ax=b\f$
 */
void solve();
```

which does an unnecessary line break and the first `\` got replaced into `@` which causes the parsing to fail. 

Ideally, pressing alt + q for this scenario should leave it as is.

Relevant link: https://www.doxygen.nl/manual/formulas.html

**Comment by 20Tauri** [comment]
Thank you for reporting,

It's a bug in the DoxyDoxygen DocStyle. The inline formula wasn't marked "inline".
Will be fixed in the next release

'\' was replaced by '@' because of the `doxygen_command_prefix` setting

In next release, your example will produce
```
/**
 * @brief      Latex formula like @f$Ax=b\f$ must not cause a carriage return
 */
void solve();
```

Note that the second '\f$' is not currently detected

**Comment by jasjuang** [comment]
Just making sure, I am sure you meant

```
/**
 * @brief      Latex formula like \f$Ax=b\f$ must not cause a carriage return
 */
void solve();
```

instead of 

```
/**
 * @brief      Latex formula like @f$Ax=b\f$ must not cause a carriage return
 */
void solve();
```

right? Doxygen wouldn't be able to parse `@f$Ax=b\f$` successfully as a latex equation

**Comment by 20Tauri** [comment]
For now the fix is not perfect, but `@f$Ax=b\f$` is correctly parsed with Doxygen 1.8

**Comment by 20Tauri** [comment]
Fixed in the Evolution version (but the mentioned limtation)
