### ISSUE TITLE
[C++] class with final modifier is not recognized

### ISSUE THREAD

**Issue by rwols** [20Tauri/DoxyDoxygen#158]
Given the following content:

```cpp
class A final {
};
```

the command doxy_comment_nearest_entity doesn't recognize `A` as a class.

In contrast, it works for this:

```cpp
class A {
};
```

**Comment by 20Tauri** [comment]
Thank you for reporting.
It's a leak in the internal grammar, `final` was not supported for class definition.
Will be fixed in the next release

**Comment by 20Tauri** [comment]
Fixed in the Evolution version
