### ISSUE TITLE
/*! comment blocks with with trailing asterisk causes odd behavior

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#16]
In the past I've used doxygen borders like this:

```
/*!********************************
@brief     stuff
@details   more stuff
**********************************/
```

I've tried emulating this style with DoxyDoxygen using this setting:

```
"prefered_comments_styles": [
  [
    "/*!********************************",
    ""
  ],
]
```

But get this odd behavior when I repeatedly use the Doxy Comment Nearest Entity command with `Super`+`Alt`+`Q` (on mac) - like I would do when trying to update an existing documentation block:

![doxygen3](https://cloud.githubusercontent.com/assets/662874/10038021/e7d2a15c-6172-11e5-8cce-7e3d3cd7b282.gif)

Since it is a valid Doxygen comment, it would be great if the updating logic in DoxyDoxygen could be adjusted to account for the exclamation mark.

**Comment by 20Tauri** [comment]
It's a funny bug.
The current interface to define style, try to match them on internal one (to be easier to configure)
In the case, this match the QT style "/_!" and the regexp "/[_]!". I uncomment using the regexp and I add your setting.

Will be fixed in next version

**Comment by JohannesMP** [comment]
:+1:

**Comment by 20Tauri** [comment]
0.19.0 released and fix this issue
