### ISSUE TITLE
can't turn off automatic newline comment insertion

### ISSUE THREAD

**Issue by bapollonio** [20Tauri/DoxyDoxygen#160]
#### Environment
    - doxy.version:        0.79.4
    - sublime.version:     3211
    - sublime.platform:    osx
    - sublime.arch:        x64
    - package_control.version: 3.4.1
    - package_control.installed: ['Advanced CSV', 'AlignTab', 'Alignment', 'CSS', 'CTags', 'Default', 'Diff', 'DoxyDoxygen', 'HTML', 'INI', 'Indent XML', 'Package Control', 'ShellScript', 'SublimeGDB', 'SublimeLinter', 'SublimeLinter-bandit', 'SublimeLinter-contrib-verilator', 'SublimeLinter-pyflakes', 'Sublimerge 3', 'User', 'xml']
    - platform.os.name:    Darwin
    - platform.os.version: Darwin-18.7.0-x86_64-i386-64bit

#### SublimeText Settings
    - translate_tabs_to_spaces: True
    - detect_indentation:  True
    - indent_to_bracket:   False
    - auto_indent:         True
    - smart_indent:        True

#### DoxyDoxygen Settings
    - autofill_rules:        [],
    - brief_mode:            preserve,
    - c_macros:              ['UCLASS()=', 'UFUNCTION()=', 'UPROPERTY(specifier, meta)=', 'UENUM(meta)=', 'KDE_EXPORT=', 'KDE_IMPORT=', 'KDE_NO_EXPORT=', 'KDE_BF_ENUM(a)=a', 'KDE_CAST_BF_ENUM(a, b)=b', 'KDE_CONSTRUCTOR_DEPRECATED=', 'K_GLOBAL_STATIC(TYPE, NAME)=', 'K_GLOBAL_STATIC_WITH_ARGS(TYPE, NAME, ARGS)=', 'Q_INVOKABLE=', 'AFX_EXT_CLASS='],
    - completion_enabled:    True,
    - completion_snippet_format: default,
    - completion_use_aliases: True,
    - continuation_on_last_multilines_comment: False,
    - continuation_on_singleline_comment: False,
    - debug_enabled:         False,
    - distance_for_bottom_line_over_top_line: 3,
    - doxygen_cmd:           doxygen,
    - doxygen_command_prefix: @,
    - doxygen_discard_param_directions: False,
    - doxygen_paragraph_prefix:     ,
    - group_tabs_sizes_by:   comment,
    - indentation_max:       99999999,
    - jsdoc_paragraph_prefix:   ,
    - max_line_reducing:     12,
    - merge_matching_ratio:  0.6,
    - min_spaces_between_columns: [1, 2],
    - notations_map:         [{'type': '~boolean~', 'regexp': '[$_]?(?:can|is|has|are)($|[A-Z_]).*$'}, {'type': 'Function', 'regexp': '(?:callback|cb|done|fn|method|next)$'}],
    - php_generate_fully_qualified_name: True,
    - phpdoc_paragraph_prefix:  ,
    - phpdoc_short_primitives: True,
    - preferred_comments_styles: [['/**', ' *'], [['/*', '-', '*//**'], ' *'], [['//', '-'], '///'], ['"""', '', '"""'], ['##', '##'], [['#', '-'], '##']],
    - preferred_line_length: 80,
    - preferred_tabs_sizes:  [12, 6, 8, 8, 8, 8],
    - preserve_aliases:      False,
    - profiles:              [],
    - profiles_default:      <not sent>,
    - proxies:               None,
    - python_func_annotations_are_types: True,
    - remove_template_used_as_type: False,
    - source_languages:      [],
    - target_language:       en,
    - translators:           [{'api_key': '', 'provider': 'google'}],
    - words_expansion:       {},

#### Edited text
    - sublime.syntax:      Packages/C Improved/C Improved.tmLanguage
    - doxy.language:       c

##### Cursor 1

```c
tatic void MultiAxisStage_RunStateMachine(multi_axis_stage_t *stage)
{
    // State transition logic
```
CURSOR (source.c meta.function.c meta.block.c comment.line.double-slash.c++ punctuation.whitespace.newline.c )

```c

    // State-specific actions
    switch(stage->state)
    {
        MULTI_AXIS_STAGE_STATE_STOPPED:
            break;
        MULTI_AXIS_STAGE_STATE_HOMING:
            break;
        MULTI_AXIS_STAGE_STATE_MOVING:
            break;
        MULTI_AXIS_STAGE_STATE_STOPPING:
            break;
    }
} // MultiAxisStage_RunStateMachine()


/*! Signals the stage that a move has been requested
 *  \param  motID   
 *  \param  dest    
 */
void MultiAxisStage_MoveAxis(multi_axis_stage_t *stage, ui
```

#### Problem description
    Turning off continuation_on_last_multilines_comment doesn't stopy DoxyDoxygen from automatically commenting in the middle of a multiline comment.  In the example above, I am trying to add code above "// State-specific actions".  I added a comment first, "State transition logic" and when I hit enter to start typing my logic, DoxyDoxygen turns the new line into a comment.

    To send it, please use 'Send Report' from the Command Palette (Ctrl+Shift+P) or Contextual Menu (Right-Click)

**Comment by 20Tauri** [comment]
Thank you for reporting,

`continuation_on_last_multilines_comment` only affect <kbd>Enter</kbd> when the cursor is on the last lin of a multi-lines comment

```c
// 'Enter' here will make the comment continue
// 'Enter' here will NOT make the comment continue if `continuation_on_last_multilines_comment` is False
```

Use <kbd>Shift</kbd>+<kbd>Enter</kbd> to insert newline easily if this case.

If you really dislike it, it's also possible to overload the KeyBinding to always insert a newline.
