### ISSUE TITLE
Possible to add custom lines?

### ISSUE THREAD

**Issue by graylaurenm** [20Tauri/DoxyDoxygen#164]
I'd like to customize the default block behavior.

For example, DocBlockr includes @ since , which I'd like to have by default.

Similarly, there's an option to insert lines. For example, in their user settings I have: `"jsdocs_extra_tags": ["@since ${1:[version]}", "@author   Name <email>"]`. Is this an option without writing a custom doc-style?

**Edited** to add space between "@" and "since" to prevent user tag.

**Comment by 20Tauri** [comment]
Use `block_layout_default`

**Comment by graylaurenm** [comment]
Thanks @20Tauri. I'm looking at `block_layout_default` and the documentation says:
> Positioning of the commands that can be present in the documentation block.
> See block_layout for further informations on format.
> Warning: SHOULD NOT BE OVERLOAD BY USER (use block_layout instead)

How should the setting be "used" then? I'm accustomed to seeing the settings look something like `"block_layout_default": "PhpDoc"` but that's not working and I don't see any examples in the documentation.

I do see that PhpDoc should have these two lines:
```
                    "@author           {user_name:doxy_capitalize();}",
                    "@since            {now:%Y}"
```
Neither are in the doc block that's generated for me, though.

**Comment by graylaurenm** [comment]
I'm able to completely override the whole block's logic, but I don't think I've gone about this the ideal way.

```
    "block_layout": {
        "PhpDoc": [
            {
                "tags": [
                    "",
                    "@_brief",
                    "",
                    "@since            1.0.0",
                    "",
                    "@author           graylaurenm",
                    "",
                    "@var",
                    "",
                    "@param",
                    "",
                    "@throws",
                    "",
                    "@return",
                    ""
                ]
            }
        ]
    }
```

**Comment by 20Tauri** [comment]
You haven't read to whole section
```
                     "@author           {user_name:doxy_capitalize();}",
                    "@since            {now:%Y}",
```

```
                    { "key": "row",      "operator": "lower_than",     "operand": "2" },
                    { "key": "kind",     "operator": "equal",          "operand": "" }
```

to seen the result, create an empty php file and press enter on the part marked "<press enter here>"
```
<?php
/** <press enter here>
>
```

I made a mistake but you corrected me: `block_layout` extends `block_layout_default`. This is the right setting to use and the right way to do it at the moment (`block_layout_default` remains active).
What would be "perfect way to do" according you ? What would you like to write ?

There's no way to add something after the docblock like `jsdocs_extra_tags`, but you can choose the tags location (and the selection of`block_layout` according a context). The setting is slighty longer but you only write once and have more options to suit your needs.

**Comment by graylaurenm** [comment]
>You haven't read to whole section

I have read the whole section. And many other sections, actually. I'm asking for information here because it's unclear without further documentation and given my current understanding level. I appreciate you taking the time to respond to me.

```
                    { "key": "row",      "operator": "lower_than",     "operand": "2" },
                    { "key": "kind",     "operator": "equal",          "operand": "" }
```

You've added these lines, but added no additional context... I don't know what these mean. Are they a form of logic that dictates whether the previous lines are added? What are they looking at? If the function is less than two rows and... has no 'kind'? If I search for "operator" or "operand" on http://20tauri.free.fr/DoxyDoxygen/v2/page_overview.php to try and understand how you're using them, there are no results. So I _have_ attempted to do my research before reaching out here.

```
                     "@author           {user_name:doxy_capitalize();}",
                    "@since            {now:%Y}",
```

Since this is default in PhpDocs... why doesn't it show up? How do I define `user_name`?

>I made a mistake but you corrected me: `block_layout` extends `block_layout_default`. [...] What would be "perfect way to do" according you ? What would you like to write ?

I was getting hung up on the specific function you asked me to use. If the method I'm using is the best way to add new lines or format existing ones, I'm good with the current implementation.

>There's no way to add something after the docblock like `jsdocs_extra_tags,` but you can choose the tags location (and the selection ofblock_layout according a context). The setting is slighty longer but you only write once and have more options to suit your needs.

I'm guessing this is probably beyond my abilities given the information I have available. My understanding is that I could simplify my previous code and add a "context" block to define when (and where) it's added to the existing `block_layout_default` lines. But, again, I can't find any documentation on that. Any insight on this?

**Comment by 20Tauri** [comment]
First of all, thank you for taking the time to understand this plugin

The default `phpdoc` section have 2 parts. The first one is for generating the file header and the second one is for document entities (functions, classes...)
You don't have to use it. I have simply try to explain why the  `@author`, `@since` don't appear in your first test (with default settings)

No condition means "always" (and `tags` of first match is used).

`user_name` is based on environment variables (USER, USERNAME, LOGNAME...). It's not the problem here (it's the `context`).
You can replace `"@author           graylaurenm"`  by `"@author           {user_name:doxy_capitalize();}"` in your example. Should work.

[Customization Page](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php) explains how `context` work. I know you already read `block_layout` and I know it's complex. But you guess right. To be brief, `context` is similar to the [sublime text “context” format](http://docs.sublimetext.info/en/latest/reference/key_bindings.html#context-reference)

**Comment by graylaurenm** [comment]
Awesome, thanks, @20Tauri! I can't get your second link to load but I found what's probably [the same content at another link](https://www.sublimetext.com/docs/key_bindings.html#context). :)
