### ISSUE TITLE
Is there an option to add a line between sections?

### ISSUE THREAD

**Issue by graylaurenm** [20Tauri/DoxyDoxygen#165]
In DocBlockr this setting is called `jsdocs_spacer_between_sections` and results in blocks that looks something like:

```
/**
 * [description]
 *
 * @since   [version]
 *
 * @author  [name]
 *
 * @param   [type]     $[var]  [description]
 * @param   [type]     $[var]  [description]
 *
 * @return  [description]
 */
```

**Comment by 20Tauri** [comment]
Use `block_layout_default`.
Let me know if this is still not clear to you after reading the user manual.

**Comment by graylaurenm** [comment]
Related: https://github.com/20Tauri/DoxyDoxygen/issues/165. Can probably close/merge this one since you're saying the solution is the same.
