### ISSUE TITLE
Exception when starting docstring inside Python dataclass

### ISSUE THREAD

**Issue by FHTheron** [20Tauri/DoxyDoxygen#169]
#### Environment
    - report.date:         2022-11-23 15:34:07.820696
    - doxy.version:        0.80.0
    - sublime.version:     4141
    - sublime.platform:    osx
    - sublime.arch:        x64
    - package_control.version: 3.4.1
    - package_control.installed: ['Copy Filepath With Line Numbers', 'Default', 'DoxyDoxygen', 'EditorConfig', 'IPython Notebook', 'JSON Reindent', 'LSP', 'LSP-json', 'LSP-pylsp', 'LSP-pyright', 'Package Control', 'PackageDev', 'ProjectManager', 'PyenvEnv', 'Terminus', 'iOpener', 'xml']
    - python.version:      3.3.6
    - python.compiler:     GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)
    - python.implement:    CPython
    - platform.os.name:    Darwin
    - platform.os.version: Darwin-22.1.0-x86_64-i386-64bit
    - platform.cpu:        i386
    - platform.arch:       x86_64
    - platform.uname:      (system='Darwin', node='Francois-H-Therons-MacBook-Pro.local', release='22.1.0', version='Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64', machine='x86_64', processor='i386')
    - sys.recursionlimit:  1000

#### SublimeText Settings
    - translate_tabs_to_spaces: True
    - detect_indentation:  True
    - indent_to_bracket:   False
    - auto_indent:         True
    - smart_indent:        True

#### Edited text
    - sublime.syntax:      Packages/Python/Python.sublime-syntax
    - doxy.language:       python

##### Cursor 1

```python
from dataclasses import dataclass


@dataclass
class Something:
    """
```
CURSOR (source.python comment.block.documentation.python )

```python

    aaa: int

```

#### Exception
```python
Traceback (most recent call last):
  File "/Users/francois.theron/Library/Application Support/Sublime Text/Installed Packages/DoxyDoxygen.sublime-package/Doxy.py", line 342, in run
    doxy_enter_command_run(self.view, edit)
  File "doxy_libs\SublimeCommands.py", line 453, in doxy_enter_command_run
  File "doxy_libs\DoxyBlock.py", line 145, in to_snippet
  File "doxy_libs\DoxyBlock.py", line 796, in _lines_to_snippet_and_indent
  File "doxy_libs\SublimeHelpers.py", line 167, in get
  File "doxy_libs\SublimeHelpers.py", line 132, in <lambda>
  File "doxy_libs\SublimeHelpers.py", line 101, in _preferred_line_length
TypeError: int() argument must be a string or a number, not 'list'

```

#### Problem description
    When trying to add a docstring to a Python dataclass, error happens when pressing
    enter after three quotes. The plugin does not need to support this, but it should
    not distract from editing.

    To send it, please use 'Send Report' from the Command Palette (Ctrl+Shift+P) or Contextual Menu (Right-Click)

**Comment by 20Tauri** [comment]
Thanks for the report.

What is the value of the "rules" parameter in your sublime text settings?
It looks like a list of list... and an invalid value.

But, the plugin must not "crash" anyway, a protection will be added to overcome this

**Comment by FHTheron** [comment]
I think you got it.
```
	"rulers":
	[
		[88, "dotted"]
	],
```

It's not invalid, but it is weird. The LSP-json linter doesn't like it and marks it as a warning.

For reference, the Sublime default preferences file says this:
```
	// Columns in which to display vertical rulers. You can also pair the column
	// with a ruler style (See "ruler_style"), eg: [[80, "solid"]]
	"rulers": [],
```

Now that I changed that back to a simple integer, this plugin does not crash. Since I was using the dotted style which is the default style anyway, this is not exactly a loss. Thanks.

**Comment by 20Tauri** [comment]
Thank, I will support this 'new' SublimeText feature in the next release

Adding this in the DoxyDoxygen settings is another way to solve the problem (if someone have the problem and want another style)
```
"preferred_line_length": 88,
```

Thanks

**Comment by 20Tauri** [comment]
Fixed in https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.81.3
