### ISSUE TITLE
"prefered_comments_styles"

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#18]
"_prefered_" in `prefered_comments_styles` is <a href=https://en.wiktionary.org/wiki/prefered>misspelled</a> and should be `preferred_comment_styles` instead.

Also, there are multiple instances of "_prefered_" in both settings comments and parameters that _really_ should be fixed.

**Comment by 20Tauri** [comment]
In next release, I will fix the default settings... still being compatible with the existing user configuration

**Comment by 20Tauri** [comment]
Fixed in 0.19.3.
For a time, both parameters will be supported
Thanks again for reporting
