### ISSUE TITLE
Request: Option to shift tag body to next line

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#23]
I'd like to have the option to create comments like this:

```
/*!******************************************************************
@brief
  Dynamically allocate a new Element Node. Handles memory allocation errors.
@param  pos
  The position of the node in the list.
@param  data
  The value at the given position in the list.
@return
  The new Element Node.
*/
ElementNode *ElementNode::MakeNode(int pos, int data)
```

Effectively the column settings would be ignored and the body of each tag shifted to the next line with some manner of indentation.

**Comment by 20Tauri** [comment]
According my tests, Doxygen produces incorrects output (HTML ...) when the paragraph not start on the same line than the "@tag". So DoxyDoxygen is design to "protect" the developer...

Do you use Doxygen or another similar tool ?
According me, the first is to check, if with your Doxygen version and your example, the output is correct.

I will make the changes to be able to have tags completely left-aligned
(https://github.com/20Tauri/DoxyDoxygen/issues/20 - point 3)

It's also possible to change the behavior on return. See https://github.com/20Tauri/DoxyDoxygen_contrib_HeaderDoc
But we cannot currently add a carriage return in command...
I will ;
    - add the capabilities to overload commands
    - handle properly "\n" in command

This may take time ;-(... To update existing comment, DoxyDoxygen is able to batch comment formatting:
- from palette, "Doxy: Select Comment" -> "Doxy"
- then "Doxy: Update command including style"

Regards,

**Comment by JohannesMP** [comment]
Hmm, I'm using doxygen 1.8.10, with mostly default settings (just html), and so far I thought I wasn't experiencing any incorrect output.

Could you give me a specific example of a tag that breaks if used like:

```
@tag
  Some Text Here
```

As opposed to:

```
@tag   Some Text Here
```

I'm just curious if I've been using it wrong so far, and if so how much that may have impacted my docs.

Thanks again for putting in all this work.

**Comment by 20Tauri** [comment]
In my memory, "paragraph" sometimes now to "detail" section...
But, with 1.8 I cannot reproduce it... Maybe a confusion between "line parameters" and "paragraph parameters"... As I prevent line break before the first word of a paragraph to avoid a non existing problem, in addition to your request, I've have a bug in the wrapping function...

**Comment by 20Tauri** [comment]
0.22.0 has this functionality.
You can add commands per command a "\n" or not.
I have also add an option "doxygen_paragraph_prefix", this option will help you to have the expected behavior without having to write your own plugin.
