### ISSUE TITLE
How to go to next line without breaking TAB order?

### ISSUE THREAD

**Issue by CieNTi** [20Tauri/DoxyDoxygen#24]
Hi there!

First of all, thanks so much for this very nice package. I just tested it and works like a charm, but I'm in doubt about how to pass to next line without loosing the <kbd>TAB</kbd> movement.

This is my case:
- I always stick to 80-width (exactly a maximum of 79)
- When I reach this limit, if I press <kbd>Enter</kbd> I go to next line, but below `@command` not below comment itself
- If I press <kbd>TAB</kbd> now, the next field or the end of comment block is actived, loosing focus of the unfinished comment.

It's possible to get this behaviour?

It's possible for you to stick the fields to a tab-stop place? In my tests (using 2 spaces "tabs") the param description is unaligned

```
/**
 * @brief      Set the next queue active
 *
 * @param[in]  target_QUE  Interrupt number to set. See long_test_file.h or
 *                        similar
 *
 * @return     { description_of_the_return_value }
 */
```
- The word `Interrupt` after `target_QUE` is unaligned
- The word `similar` alone in the line, is aligned. I moved this word after finishing TAB movement, then arrows and tab.

If you copy&paste this bit of code inside ST3 with 2 pure space tabs you'll check it

Thanks so much in advance for your support, and please excuse my english.

CieNTi

**Comment by 20Tauri** [comment]
Hi,

### Point 1

I may change the plugin to automatically been on the "right" column in this case.
Currently, you have 2 ways to "solves" your problem.
- Press <kbd>EOL</kbd> twice. Cursor will move to the "right" column
- Do try to align text. Press <kbd>Alt</kbd>+<kbd>Q</kbd> once your comment is written.

I try to improve the workflow to be as simple as possible... Not always easy to find the "best" choice... You may want to add a new "@tag"...

### Point 2

If you have change the default settings, you will have 2 spaces between parameters name and description. That is the expected behavior. See following parameters

```
    "min_spaces_between_columns": [ 1, 2 ],
```

But you're right, it's strange "similar" have to been aligned. Which version do you use ?
Copy&Paste your code and pressed <kbd>Alt</kbd>+<kbd>Q</kbd> work for me... Text is aligned.

May I have your settings ? (you can use the contextual menu "doxygen report" -> "anomaly report" to send it easily)

**Comment by CieNTi** [comment]
#### Point 1

Oh man ... i just realized you already wrote that <kbd>EOL</kbd> on readme file, very sorry for asking an already explained thing. It works perfect.

I tried <kbd>Alt</kbd>+<kbd>Q</kbd> once written and as you said, it vertically align with the correct parent column.

Thanks for your patience

#### Point 2

Tell me if this is enough for you: [My user files](https://github.com/CieNTi/user_files)

Anyway you can see here with the same example:

```
/**
 * @brief      Set the next queue active
 *
1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9
 * @param[in]  target_QUE  Interrupt number to set. See long_test_file.h or
 *                        similar
 *
 * @return     { description_of_the_return_value }
 */
```

In a pure 2 spaces indent environment, each number is an aligned position, and each space is unaligned so just see how `Interrupt` start in a "space" place, and `similar` in the second "5".

About spaces between columns default setting is ok for me, but anyway still not act preserving indent alignment, because both (1 and 2 spaces) can fail if param name is one character longer or shorter.

My first idea about this is to create a kind of bool setting for that, and if enabled try to comply with `min_spaces_between_columns` but if is unaligned, add one extra space. It makes sense to you?

And again, thanks for the package, it's really useful to me.

**Comment by 20Tauri** [comment]
I'm not sure to understand

Taken from documentation:

``` c
    // First number  is for first column
    // Second number is for second column
    // ...
    // Last number is applied to all next columns
    //
    // For example, a value of [1, 2] might look like this:
    //
    //              +-- At least 1 space here (but according "tabs" it's more)
    // /**          V    V--- At least 2 spaces here
    //  * @param[in]  foo       Lorem ipsum dolor sit amet.
    //  * @param[out] long_bar  Nullam fringilla feugiat pretium. Quisque
    //  */
```

More spaces may be add if necessary (to match `preferred_tabs_sizes` constraint)
If parameters names are longer than `preferred_tabs_sizes` the longest is used.
So indentation should be preserved. No additional parameters are needed

I've made a test with your settings (there's no DoxyDoxygen settings ?), It works fine for me (on both 0.21.0 and 0.22.2). Which version do you use ?

Just to be sure. Upgrade package. Restart sublime text...
If problem persist, please place the cursor on the command and contextual menu. "Anomaly Report (integrated agent)." If you have, you probably have to upgrade

Let me know if it solve your problem

**Comment by CieNTi** [comment]
What I understand is that I should change the second value of `preferred_tabs_sizes` to something bigger. If not, as the param name is longer, the `min_spaces_between_columns` second value will be used.

But I mean "the space width between 2nd and 3rd column will be `min_spaces_between_columns` second value if starts in a tab_stop, or add the neccesary to match a tab_stop"

I prepared ST3 to have one guide each 2 spaces (mimic my 2 space indenting valid positions). As you will see, i'll appear 2 examples. The difference is the param name: One is `*_QUE` and the next one have one more char `*_QUEe`.

At first example, param description don't match a tab_stop. As soon as one char is added, it fits perfect.

![st3_doxydoxygen](https://cloud.githubusercontent.com/assets/5205702/10528246/5ce2eea0-7395-11e5-97b3-8c2939763aad.gif)

Anyway, I understand not all the people use spaces for indenting, and can be wider as 4 o 8 spaces long ... so, the <kbd>EOL</kbd> thing it's good for me ... I tried tabs to move because this feature was unknown for me before asked you.

**Comment by 20Tauri** [comment]
You are right,
Currently, there's no way to force alignment on a column if name length exceed reversed spaces... and there is no plan to add this feature (nobody request it)
I agree with you, tabs should be used only for indentation in first column...

According me, the best way to solve alignment is to use <kbd>Alt</kbd>+<kbd>Q</kbd>.
Using this comment, the comment will be "up to date" and "correctly aligned" according the commands settings. I no longer use `/**``+<kbd>Enter</kbd> is fact...

You have seen yet, but the <kbd>EOL</kbd> method may fail in version prior than 0.22.5. Incorrect aligned occurred when there are severals parameters. This command played on the first parameter, with a second parameters greater than the first one and greater to `preferred_tabs_sizes` cause missing spaces.

I also slightly change the behavior of <kbd>EOL</kbd>. You will no longer have to press twice this key.

Thanks you for reporting and do not hesitate if you have more questions or suggestions.
