### ISSUE TITLE
How can I switch to a different "preferred comment style"

### ISSUE THREAD

**Issue by a-barbieri** [20Tauri/DoxyDoxygen#25]
Hi there,
I've been using DoxyDoxygen on Sublime Text for a while, but I think I missed one feature though. 
I set up my `preferred_comments_styles` in the user settings and eventually I wanted to use a different one to create a sort of hierarchy between functions.

At the moment is like this

```
{
    "preferred_comments_styles": [
        [
            "// - - - - - - - - - - - - - - - - - - - - - - - - - - -",
            "// ",
        ],
        [
            "// ======================================================",
            "// "
        ]
    ]
}
```

Is it possible to switch to a different style while typing?
I tried several ways but I couldn't find any documentation on the subject.

Thanks

**Comment by 20Tauri** [comment]
Hi,
Perhaps the commande "Comment Update Preserving Style" may help (the default shortcut is <kbd>Alt</kbd>+<kbd>Q</kbd>.

Example:

``` js
///Alt+Q 
function ciao(nome)
```

will produce

``` js
///
/// @method     ciao
/// @param      {<type>}  nome    { description }
/// @return     {<type>}  { description_of_the_return_value }
///
function ciao(nome)
```

While

``` js
/**Enter
function ciao(nome)
```

will produce (according your style)

``` js
/*----------------------------------------------------------------------*//**
 * { function_description }
 *
 * @method     ciao
 * @param      {<type>}  nome    { description }
 * @return     {<type>}  { description_of_the_return_value }
 */
function ciao(nome)
```

For the second example

``` js
/**
*/
function ciao(nome)
```

For this second example your may also use

``` js
/*-*//**Alt+Q
 */
function ciao(nome)
```

In your example: "// ="<kbd>Alt</kbd>+<kbd>Q</kbd> is the "best" way to have the expected result.
Unfortunaly, this will not work but make the change for the next release.

Regards,

**Comment by 20Tauri** [comment]
0.25.3 was just been released and should fit your need.

**Comment by a-barbieri** [comment]
Thank you, I'll check it today!

Best

Inviato da iPhone

**Comment by 20Tauri** [comment]
This probably work... I close the ticket

**Comment by a-barbieri** [comment]
Hi 20Tauri,

I haven't had the time to come back to you since now.

The update you made works but not entirely.
As you now I have two preferred styles ([see first post](https://github.com/20Tauri/DoxyDoxygen/issues/25#issue-116994773)).

If I want to get the second of my preferred styles I type `// =` and then pressing `Alt` + `Q` (+ `⌘` as I'm on OSX). As a result I get the following line, which is correct:

```
// ======================================================
```

the issue is that it doesn't return down. Besides, if immediately after I hit `return`, it switches back to the first style and I get this:

```
// - - - - - - - - - - - - - - - - - - - - - - - - - - -
// 
//
```

Is it possible to fix it?
Thanks.

**Comment by 20Tauri** [comment]
Hi Alessandro,

You're right, as there's no newline, <kbd>Enter</kbd> is pressed on a comment start... And the plug-in default behavior in this case is to convert it to the preferred one, the result seem amazing. To avoid this you can press <kbd>Shift</kbd>+<kbd>Enter</kbd>... But it's not intuitive, nor efficient...

I will probably add a newline (for single line comment) in next release... and perhaps modify the behavior on <kbd>Enter</kbd> to find the closest style if it's a non trivial one (///, ##...)

In fact, I never detect this case, because I prefer define the entity to document before.
In your case, can be something like this:
-  "// ="
- then <kbd>Shift</kbd>+<kbd>Enter</kbd>
- then "function doSomething()  {}"
- then <kbd>Alt</kbd>+<kbd>Q</kbd>

This workflow seem efficient... What do you think about it ?

**Comment by a-barbieri** [comment]
It makes sense.

One question: after <kbd>Shift</kbd> + <kbd>Enter</kbd> am I able to write the description?

In fact what I would do is:
- type `// =`
- press <kbd>Shift</kbd> + <kbd>Enter</kbd> in order to get this lines:

```
// ======================================================
// 
//
```
- type `function description`
- declare `function foo()`
- once the function is completed I'd update the header by pressing <kbd>Alt</kbd> + <kbd>Q</kbd> ( + <kbd>⌘</kbd>)

**Comment by a-barbieri** [comment]
It'd be good to consider that one person might want to have this two styles:

`//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -`
`//---------------------------------------------------------------`

In this case, shall I do call them this way: `//- -` and `//--`?
Or would it be best to press <kbd>Shift</kbd> + <kbd>Enter</kbd> one time to get the first style and two times to get the second of the list?

**Comment by 20Tauri** [comment]
No, <kbd>Shift</kbd>+<kbd>Enter</kbd> is a regular "Return" (not handled by this plugin) so not this will be added. You can enter "// + description", this will work. On update, the description will be detected and preserved.

Alternatively, with version 0.28.4 (released yesterday), the suggested newline is added... So, "// =" <kbd>Alt</kbd>+<kbd>Q</kbd>Will also work now and if there's no definition, will simply prompt for a description...

"Multiples styles" is a very interesting subject.

Current solution (working fine with 0.28.4) is:
- "//- ", then <kbd>Alt</kbd>+<kbd>Q</kbd>
- "//--", then <kbd>Alt</kbd>+<kbd>Q</kbd>

Others solutions (non working yet) can be:
- Style Detection using preceding pattern when pressing kbd>Enter</kbd>
- Style change command (doxy_reparse already allow this but only to the preferred one)... but I can add an option to selection the style interactively

> <kbd>Shift</kbd>+<kbd>Enter</kbd> is a regular "Return" (and is just a way to prevent a "new" comment creation). My previous message is probably unclear on this point

**Comment by 20Tauri** [comment]
I have added a now command "Command Update With User-Selected Style" in 0.29.0 (evolution branch). 
Currently only available from the palette

May be another way to answer multiple style... I'm not sure to it s the best and a shortcut can be added if you have intensive usage.

Every feedback and suggestion are welcome

**Comment by a-barbieri** [comment]
I use it very often as it makes longer code clearer.

At the moment I'm using 0.28.4 and I'm testing it.
Once you'll release the 0.29.0 I'll test the command as well.

Looking forward.
Thanks

**Comment by 20Tauri** [comment]
Regular version 0.29.6 has being released and include this change.
The update_comments command may be improved in future according the survey feedbacks
