### ISSUE TITLE
Setting a single language's block_layout

### ISSUE THREAD

**Issue by teroyks** [20Tauri/DoxyDoxygen#26]
Is there a way to update the "block_layout" setting for just one language (e.g. "ApiDoc") without copying the whole "block_layout" section into my user preferences?

**Comment by 20Tauri** [comment]
No, currently there's no way to do this...
I agree that it's an important improvement point for this plugin...
But I'm not sure that docStyle (ex ApiDoc) is the only thing to check... According me, it's also interesting to allow to check the documented object type (class, method, var...)

**Comment by 20Tauri** [comment]
I will add "block_layout_default" with the current "block_layout" content
"block_layout" will become the user overload.
Seem to be the best for compatibility... I will improve format, to fit other needs, in a second step.

This will be done in the next release

ps: As ApiDoc is new, all suggestions to improve the default layout are welcome.

**Comment by 20Tauri** [comment]
DoxyDoxygen 0.26 now have this capability.
Currently only available in "evolution" branch
