### ISSUE TITLE
Changes to user preferences require restart to take effect

### ISSUE THREAD

**Issue by JohannesMP** [20Tauri/DoxyDoxygen#27]
This may be a recent thing since I don't remember it happening before, but as far as I can tell, changes made to my DoxyDoxygen user preferences don't currently take effect until I restart sublime.

**Comment by 20Tauri** [comment]
I've tried in several configuration (not os/x unfortunately), but I cannot reproduce...
We probably use the same version of sublime text (3084 for me) and you probably use the lastest Doxygen version (0.26.0)...
- Have you got the problem every time ?
- Is the problem occurred on all parameters ?

I'm not sure that is configuration dependant, but if you have an user preference file and a field that cause problem, I can try again...

**Comment by 20Tauri** [comment]
Are you still have this configuration update problem ?
Is someone else have this problem ?

**Comment by 20Tauri** [comment]
I have added a specific question in my last survey about this problem:
http://20tauri.free.fr/DoxyDoxygen/survey/results.php?survey=762ed51
No one else seem to be affected by this problem.

Is DoxyDoxygen the only plugin affected by this problem ?
This problem can be really annoying (for someone who like change configurations frequently).
Have you still have the problem from a fresh installation with only the plugin installed ?
