### ISSUE TITLE
Should be able to generate FQN for param types.

### ISSUE THREAD

**Issue by ifeltsweet** [20Tauri/DoxyDoxygen#29]
At our codebase we use fully qualified names when documenting parameter types.

Instead of `@param View $view` we do `@param \Illuminate\View\View $view`.

I generally think this is a good practice. Can it be done with DoxyDoxygen?

**Comment by 20Tauri** [comment]
Yes, and it's the default. Here a result of the test suite

``` php
<?php
/*----------------------------------------------------------------------*//**
 * { function_description }
 *
 * @param      \NS\ClassA  $a      (description)
 * @param      \NS\ClassB  $b      (description)
 */
function fname(\NS\ClassA $a, \NS\ClassB $b = null) {}
?>
```

Do you have a non working example ? or it's just a question ?

**Comment by ifeltsweet** [comment]
Sorry, I should have been more specific.

What you showed definitely works, but we don't usually have FQN in parameters because most of the time we alias classes with a `use` statement:

``` php
<?php

namespace Ns1; 

use Ns2\ClassA;

/**
 * { function_description }
 *
 * @param  ClassA  $a      (description)
 */
function fname(ClassA $a) {}
```

Hope this clarifies the issue.

**Comment by 20Tauri** [comment]
Not (yet) possible... 
Not planned for now.
If other people are interested in it, please join the conversation

**Comment by 20Tauri** [comment]
Added in DoxyDoxygen (evolution branch)
https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.29.2

**Comment by 20Tauri** [comment]
Added in regular version

**Comment by ifeltsweet** [comment]
Wow, beautiful work.

One last thing to make it work completely correct is to prepend FQCN with `\` (root namespace):

It has to be `\Acme\Core\Vote\PollChoice` instead of `Acme\Core\Vote\PollChoice`. The leading `\` removes any doubt about which class we are referring to. That is because in PHP when you are inside a namespace if you don't use a leading slash then you will be accessing children of the current namespace which is not what we usually mean. The only exception to this rule is for the `use` keyword.

To illustrate (pay attention to leading slashes):

``` php
<?php

namespace Acme\Core\User;

// Refers to \Acme\Core\Vote\PollChoice. Notice we don't need a leading slash
// here because `use` statements by default start lookup from the root namespace.
use Acme\Core\Vote\PollChoice;

// Refers to \Acme\Core\User\Acme\Core\Vote\PollChoice, which is not what we usually want.
new PollChoice = Acme\Core\Vote\PollChoice();

// Refers to \Acme\Core\Vote\PollChoice, which is what we want.
new PollChoice = \Acme\Core\Vote\PollChoice();

// Refers to \Acme\Core\Vote\PollChoice. This is because we aliased this class with
// the `use` statement.
new PollChoice()
```

As you can see from the above example, if we don't have a leading slash then our FQCN can mean different things depending on which namespace we are currently in. Of course, if we are not in a namespace (means we are actually inside root namespace) then a leading slash is not needed because all other namespaces are children of root namespace and the slash will be prepended automatically.

Very impressed by your work, will definitely recommend this plugin to friends and will buy licenses for my other developers. Cheers.

**Comment by 20Tauri** [comment]
Thanks,

I've added the missing `\` in version 0.30.0. Here, an example taken from the new tests suite.

``` php
namespace Ns1;

use Ns2\ClassA;

/**
 * { function_description }
 *
 * @param      \Ns2\ClassA  $a      (description)
 */
function fname(ClassA $a)
{
}
```

Thanks you for the recommendations, create a community around this plugin is important for me.
Users usually provide the best ideas. And, as everyone, I like when my work is useful for someone.

Regards,
