### ISSUE TITLE
Allow to tab through guessed types.

### ISSUE THREAD

**Issue by ifeltsweet** [20Tauri/DoxyDoxygen#31]
Currently if the type of parameter can be guessed there will not be a tab stop for it. Since #29 is not likely to be implemented any time soon, enabling a tab stop for parameter type can be very helpful to PHP users who can expand class name into an fully qualified class name using a keyboard shortcut (from Sublime PHP Companion). This will allow for a fast workflow without having to use mouse to select each parameter type.

Obviously, this should be an optional configuration since not everybody will be needing it. Will be highly appreciated.

**Comment by 20Tauri** [comment]
Seem to be very important for you.
Even if I will probably rewrite this part in a far future, #29 will be implemented in a next release

**Comment by 20Tauri** [comment]
Won't be addressed as #29 was done
