### ISSUE TITLE
php dockblock auto update is broken

### ISSUE THREAD

**Issue by mikk150** [20Tauri/DoxyDoxygen#38]
when trying to update PHP docblock it messes up the start of the dockblock

say I have comment

```
    /**
     * Adds token to user
     *
     * @param      User    $user       user to send token to
     *
     * @return     string  Token UUID
     */
```

then I press alt+shift+Q to update it and result is 

```
    /*=======================================================================*//**
     * Adds token to user
     *
     * @param      User    $user       user to send token to
     * @param      string  $tokenType  (description)
     *
     * @return     string  Token UUID
     */
```

I even tried to edit the config file

``` json
{
    "preferred_comments_styles": [
        [
            "/**",
            " *"
        ]
    ],
}
```

**Comment by 20Tauri** [comment]
This sounds comment style detection problem.
0.34.x serie have a lot of changes in this part, but your testcase works fine for me (0.34.3)

You don't have to force `preferred_comments_styles`, using default DoxyDoxygen try to preserve style on existing comment (but your settings are ok)

Please check you have the last version then restart SublimeText
If it still not work,can you give sublime text version and platform used ?

Thanks,

**Comment by 20Tauri** [comment]
I plan to upgrade the regular branch.
It will be great if you can confirm me that your problem is solved.

**Comment by 20Tauri** [comment]
Anyone else have this problem ?

**Comment by 20Tauri** [comment]
Seem solved... 
Please reopen it if problem persist
