### ISSUE TITLE
Ignore a regex in the function signature

### ISSUE THREAD

**Issue by Eyenseo** [20Tauri/DoxyDoxygen#39]
Hello,

I would like to know if it is possible for you to add the option, to add a regex that will be ignored/removed from the function signature, before the signature is parsed?

WHY?!?! 
macros ... evil beasts ...

``` cpp
void Ma(cro) Foo(int a, int b);
```

I would like to specify a regex: 

```
Ma\(.*?\)
```

that will be ignored / removed from the function signature.

**Comment by 20Tauri** [comment]
Hello,

Have you got a real use-case ?

DoxyDoxygen support a lot of standard extensions like __assume, __declspec... 
If it's standard is probably worse been ignored by default.

Usually, in this case macros have no argument (look like API_CALLBACK...)
DoxyDoxygen already support it (and try to make difference been type and macros)

Regards,

**Comment by Eyenseo** [comment]
@20Tauri thank you for the fast reply! 

> Have you got a real use-case ?

Yes the one I showed - we have indeed a Macro like the one I showed.

If a regex is to complicated, it would be sufficient to have an array of strings that will be ignored from the signature - that way I could blacklist Ma(cro), Ma(foo), aso.

**Comment by 20Tauri** [comment]
Regexp is not the main problem... even if there's evil trap
- void what_is(const char *my_default_value = "Ma(tch) my regexp ?")

I would like to avoid unnecessary options...
A macro here look really unusual, that why I have ask for a "real" example (your macro is probably not "Ma")
This example is also not so ambiguous: "no ";" no "{" after... Not there easiest way... But it's a way

**Comment by Eyenseo** [comment]
@20Tauri 
Yes it is unusual - we use it for `__declspec` and `__attribute__`. With the parameter of the macro we can select which one of the two should be used. If I get the permission I will make that header public as it's quite nice (evil ... but nice nonetheless).

Your example makes it quite clear that a regex is not an easy and safe solution - like I mentioned before, as long as I can exclude an arbitrary string from the signature I would be happy.

A regex that could work for me would be this one: [`^.*?(Ma\(.*?\))(?=.*(?:\(.*\))+[^\)]*$)`](https://regex101.com/r/rA3uG8/3)

The rege could be simplified as it had to be a little bit more complex for the multi-line testing.

**Comment by 20Tauri** [comment]
It's more common to used specific macro in this case like IMPORT_DIRECTIVE (without parenthesis that is expanded in __declspec(dllimport) for example). This is usually more flexible and more portable

DoxyDoxygen may be designed to support RegExp like in your example without causing the issue of me second example... May be added in a future version.

Sound like a C, C++ specific option...
If anyone have this kind of need for another language, please leave a comment here. This will help in design choose.

**Comment by 20Tauri** [comment]
It's experimental, but in 0.35.5, I've slighty improved the C parser to match your use-case.
Macro name should be uppercase

**Comment by Eyenseo** [comment]
:+1: 
Works nicely, thank you very much!

**Comment by 20Tauri** [comment]
Released in standard branch too
