### ISSUE TITLE
Open source ?

### ISSUE THREAD

**Issue by ncoden** [20Tauri/DoxyDoxygen#4]
I would like to contribute

**Comment by 20Tauri** [comment]
No it not open source, but it's modular and people will be able to contribute once documentation will be done.
What kind of improvements do you want to perform ?
Some interfaces are already stable...

**Comment by ncoden** [comment]
Open Source does not mean it is in the public domain. http://choosealicense.com/
And how to contribute without the code?

**Comment by 20Tauri** [comment]
Languages parsers and Documentation styles have interfaces.
Once documented, it will be easy to contributed.
For example, you don't need to have "Sublime-Linter (core) " sources to contribute

For documentation styles (JsDoc, Doxygen...) it's even simpler
Documentation styles are mainly a list of commands. Something like that

``` python
COMMANDS_LIST = [
    DoxyCommand( '@abstract',         '',                                help = "This member must be implemented (or overridden) by the inheritor", aliases = [ '@virtual' ]),
    DoxyCommand( '@access',           '\t(private_protected_public)',    help = "Specify the access level of this member (private, public, or protected)"),
    DoxyCommand( '@alias',            '\t(name)',                        help = "Treat a member as if it had a different name"),
...
```

So it can be easily created from an JSON user configuration file

How do you want to contribute ?

**Comment by ncoden** [comment]
Ok. There is no code, it's only SublimeText configuration ?

**Comment by 20Tauri** [comment]
No there's code...
DoxyDoxygen now support plugin for DocStyle.
You may found an example on https://github.com/20Tauri/DoxyDoxygen_contrib
