### ISSUE TITLE
CUDA C problem

### ISSUE THREAD

**Issue by alvaroordonhez** [20Tauri/DoxyDoxygen#41]
The CUDA C language include some function type qualifiers that specify whether a function executes on the host or on the device and whether it is callable from the host or from the device. These qualifiers make that the auto-complete documentation don't work. I think that is easy to fix.

![example](https://cloud.githubusercontent.com/assets/4092150/13352105/6ec34a02-dc8b-11e5-9404-ed4b34d671bc.png)

Thanks you.

**Comment by 20Tauri** [comment]
I've have improved the C, C++ parser to be more compliant with some CUDA keywords (function qualifier but also variable qualifier like **manager**)
I have not added to the specific CUDA type as built-in (to still compliant with C) but shouldn't be an issue

Fix is release in 0.37.1 for both regular and evolution branch

**Comment by alvaroordonhez** [comment]
Perfect. Thank you and congratulations for the plugin
