### ISSUE TITLE
Bug: Cannot detect static Php methods

### ISSUE THREAD

**Issue by sasensi** [20Tauri/DoxyDoxygen#42]
Hi and before all thank you for your work on this plug-in !

I wanted to repport an issue with Php static methods.
Its easily reproducible with this code snippet:
<?php
class ClassName
{

```
public static function FunctionName($value='')
{
    # code...
}
```

}
?>

/*\* + enter just produces an /***/
alt+q on method name produces an error message in sublime footer : [doxy] cannot detect function... command aborted.

Hoping you can fix it.

**Comment by 20Tauri** [comment]
Thank you for reporting,

I've fixed the php parser. The result is now

``` php
<?php
class ClassName
{

/**
 * { function_description }
 *
 * @param      string  $value  (description)
 */
public static function FunctionName($value='')
{
    # code...
}

}
?>
```

I've released it in all branches.

**Comment by sasensi** [comment]
Great, thank you again !
