### ISSUE TITLE
There is a problem when using JSX

### ISSUE THREAD

**Issue by JonDotsoy** [20Tauri/DoxyDoxygen#44]
Before:

![image](https://cloud.githubusercontent.com/assets/3086539/13575222/77343330-e466-11e5-8d75-59fd84957bb0.png)

After:

![image](https://cloud.githubusercontent.com/assets/3086539/13575233/887f3414-e466-11e5-8abd-51e3c27264c4.png)

**Comment by 20Tauri** [comment]
Can you give me the action performed between those screenshots ?
With the exact cursor location ? And the result of view.scope_name(view.sel()[0].begin())...
The source as text will also be highly appreciate to reproduce it.

**Comment by 20Tauri** [comment]
Anyone else have this "strange" problem ?

**Comment by JonDotsoy** [comment]
I use [Babel Syntax](https://packagecontrol.io/packages/Babel).

In this order by **_Ctrl+Shift+h**_ (**HTMLPrettify**). And exists problem with **Javascript** And **JSX** syntax.

**Comment by 20Tauri** [comment]
Tested... I can reproduce but I've the problem even with DoxyDoxygen uninstalled ?
So I suggest you to open this issue in [HTMLPrettify repository](https://github.com/victorporof/Sublime-HTMLPrettify/issues)

**Comment by JonDotsoy** [comment]
Ho! true,
This problem is not here, thank you very much @20Tauri.
