### ISSUE TITLE
Doxydoxygen cannot recognize vector of vector

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#45]
Suppose I have a function that looks like

void test(const std::vectorstd::vector<int> &data);

Evoking alt+q will result in 

```
  /**
   * @brief      
   *
   * @param[in]  <unnamed>  { parameter_description }
   */
void test(const std::vector<std::vector<int>> &data);
```

instead of the usual

```
  /**
   * @brief      
   *
   * @param[in]  data  { parameter_description }
   */
void test(const std::vector<std::vector<int>> &data);
```

**Comment by 20Tauri** [comment]
`>>` vs `> >` problem... I use to add the space to avoid this ambiguous syntax....
Your syntax is illegal in version prior to c++11, but legal from c++11

I advice you to write

``` c++
void test(const std::vector<std::vector<int> > &data);
```

But I agree, it's a bug.

**Comment by 20Tauri** [comment]
Partially fixed in 0.38.0.
I need to determine exact type of all tokens to interpret it right... May be really difficult and time consuming as real type may be in header file (for example).

**Comment by jasjuang** [comment]
The newest update solves

```
void test(const std::vector<std::vector<int>> &data);
```

but if I am using a different type, for example cv::Mat from OpenCV

```
void test(const std::vector<std::vector<cv::Mat>> &data);
```

it will return the same error.

Thanks so much for working on this!

**Comment by 20Tauri** [comment]
I know... This subject may be really complex (usually solved using clang parser...)...
I have slightly improved my tokenizer to fix trivial cases... Will work on your new example...
But this still not work in this example (`&` removed)

``` c++
void test(const std::vector<std::vector<cv::Mat>> data);
```

Even if it's a bug, I still advise you to use c++03 syntax (for portability reasons) and to use "typedef" (for readability and reliability reason)...

If you (or someone else) have other usual c++11 cases that cause problem, I will even try to fix them...

**Comment by jasjuang** [comment]
Thanks for the suggestion on using typedef, regarding the c++03 syntax, I
am using clang format to auto format my code on save, so even if I add a
space in between, clang format will eliminate the space automatically

**Comment by 20Tauri** [comment]
Strange according [Clang-format manual](http://clang.llvm.org/docs/ClangFormatStyleOptions.html), if you use standard `LS_Cpp03` you should have a space... You probably use `LS_Cpp11`

**Comment by jasjuang** [comment]
I am using the default google coding style which most likely defaults to
LS_Cpp11. I guess I could add this additional flag to change it to be
compatible with doxydoxygen for now. Would be awesome to see it compatible
with C++11 in the future though

**Comment by 20Tauri** [comment]
Parser has been improved again... not perfect but most use cases should be now be addressed
Released in all branches

**Comment by jasjuang** [comment]
Awesome fix! Even you said it's not perfect but I couldn't detect any
problems with a few tests.
