### ISSUE TITLE
in-line doxygen comments

### ISSUE THREAD

**Issue by smykul** [20Tauri/DoxyDoxygen#50]
Hi there,

I tend to use in-line Doxygen comments in my header files (at the end of non-implemented member functions and properties). My issue is that DoxyDoxygen is carrying these comments to the next line as if they are a block comment.

For example, I may want a line to look like:

Parser(); //!< Default Constructor

But when I hit enter whilst using DoxyDoxygen, I get this:

Parser(); //!< Default Constructor
//!

(The second "//!" is generated in line with the previous "//!", i.e. at the same tab depth)

I have looked through the default configuration and tried overriding various settings in the user configuration to no avail. Apologies if I have missed something obvious, I know I can press shift+enter instead but it feels very tedious; the majority of lines in my header files use this syntax.

Thank you for your time, aside from this problem I am very much enjoying DoxyDoxygen ATM.

**Comment by 20Tauri** [comment]
Hi,

Look like the `continuation_on_last_comment` setting... Currently describe in the FAQ

I work on a new version of documentation... Here the lins
- http://20tauri.free.fr/DoxyDoxygen/page_usage.html#comment-continuation
- http://20tauri.free.fr/DoxyDoxygen/page_customization.html

Regards

**Comment by smykul** [comment]
Setting continuation_on_last_comment to false did the job! 

After reading the notes I was under the impression that this would break the adding of new lines in block comments by pressing return; I see now that this is not the case.

Apologies for missing it, and thank you for your quick response; it is much appreciated ;-)
