### ISSUE TITLE
Customising tag layout

### ISSUE THREAD

**Issue by karol-pilch** [20Tauri/DoxyDoxygen#51]
Hi,

I'm trying to customise the package to create docblocks conforming to [Drupal Coding Standards](https://www.drupal.org/coding-standards/docs#param). I've been looking at the documentation but see no way to format `@param` tags. I would love to be able to do something like

```
"block_layout": {
    "Doxygen": [{
        "tags": [
            "@param {p_type} {p_name}",
            "  <description>"
            // Or "@param {p_type} {p_name}\n   <description>"
        ],
        "context": [
            { "key": "kind", "operator": "equal", "operand": "function" }
        ]
    }]
}
```

Is it possible?

**Comment by 20Tauri** [comment]
Hi

DoxyDoxygen supports severals documentation generators.
Here you configure the layout for the Doxygen 
Doxygen have not "type" param for this command (see https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdparam)

You probably use JsDoc and want to set the "jsdoc_paragraph_prefix"...
See the default settings file

I currently work on an update of documentation... 
The search engine give a good result in your use case.
http://20tauri.free.fr/DoxyDoxygen/page_customization.php?highlight=drupal

**Comment by karol-pilch** [comment]
Thank for quick reply.

The code snippet I provided was purely an example of what I wanted to accomplish. I made up the params (`p_type`, `p_name`) just as a demonstration.

I don't use JsDoc - Drupal coding standard is Doxygen (as mentioned in the link I posted earlier), but their formatting is slightly different than what DoxyDoxygen does by default.

I managed to replace the columns with single spaces using `"preferred_tabs_sizes" = [0]`, but I can't get the paragraph_prefix to work. Adding `"doxygen_paragraph_prefix": "\n  "` makes no difference and neither does `"jsdoc_paragraph_prefix": "\n  "`. I tried setting `"preferred_comments_styles": ["Doxygen"]` to make sure that we're using Doxygen style, but I get this error in the console:

```
Traceback (most recent call last):
  File "0.45.2\ST3\TMP\doxy_libs\Comments.py", line 1339, in get_comments_styles
ValueError: too many values to unpack (expected 2)
```

I get this error with any other value put in for `preferred_comments_styles` - I tried `["JsDoc"]`, `["JsDoc", "Doxygen"]`, `["Doxygen", "JsDoc"]`, `["Whatever"]` and they all give the same error. It would be nice if the documentation had some possible values to use for that setting.

What should I do in the settings for the `doxygen_paragraph_prefix` to have any effect?

Thank you again for your help.

**Comment by 20Tauri** [comment]
"preferred_comments_styles" aims to define the decoration around the comment. "doxygen" is not the right place to force the documentation generator.

The job to map programming language to documentation generator is configurable using "profiles"
You probably develop using php... and the default doc_style is "PhpDoc"(umentor)

The closest configuration to match your need seem to use JsDoc as primary style (to have type information) and then Doxygen to have the extra tags.

Settings should look like this

``` javascript
    "profiles": [
        {
            "languages":  [ "php" ],
            "parsers":    [ "LanguagePhp" ],
            "doc_styles": [ "JsDoc", "Doxygen" ] // or "ApiDoc"
        },
    ]
```

And do not forget to remove your change in `preferred_comments_styles`

I haven't right the full article yet... I not sure the Drupal still use doxygen (I found nowhere the command line use to generate the documentation and the 'drupal-doxygen-base' don't use the @param tag)... 
For now, the right way to integrate it seem to add a new doc_style to support, "@Plugin(" and all specific Drupal tags.

**Comment by 20Tauri** [comment]
Drupal Api Module is not really Doxygen... My previous tip will not work, because JsDoc will put bracket around type... Your need is closest to PhpDoc (the original setting)
But "type" seem different "$this" vs "self" for example

So, In a next release, I will introduce a Drupal Generator...

**Comment by karol-pilch** [comment]
Thank you very much! Your settings snippet worked very well. Drupal comment generator would be absolutely amazing!
