### ISSUE TITLE
Crashing Constantly

### ISSUE THREAD

**Issue by aymaluser** [20Tauri/DoxyDoxygen#54]
The plug-in is essentially non-functional due a consistent python error issue on every command:   something about can't use a float with a sequence.  It seems to be expecting an int.

I've lost the actual back trace and have removed the package.  Seems like an easy fix, though, so I'm just letting you know.  Unless there's something crazy with my system (I'm on the latest dev build 3118), it seems that nobody could be using this plugin successfully as it's a bug or at least a regression in the plug-in python code that prevents every and all commands from working.

**Comment by aymaluser** [comment]
#### Exception

``` python
Traceback (most recent call last):
  File "Doxy in /home/lab/.config/sublime-text-3/Installed Packages/DoxyDoxygen.sublime-package", line 312, in run
  File "0.46.1\ST3\TMP\doxy_libs\SublimeCommands.py", line 377, in doxy_enter_command_run
  File "0.46.1\ST3\TMP\doxy_libs\Comments.py", line 1614, in uncommented_to_commented
  File "0.46.1\ST3\TMP\doxy_libs\Comments.py", line 109, in _get_expanded_border
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by 20Tauri** [comment]
It's look like a problem with `view.settings().get("rulers", [])`.
This probably returns a floating number in 3118. I've not installed this version yet
I will check and release a fix quickly

Thank for reporting

Tests done on 3118... Cannot reproduced (using default configuration and my own)

I've made a fix based on the stack trace (I now force `ruler[0]` to `int`)
If you want, you can try again to use the plugin.
I'm curious on the result on `view.settings().get("rulers", [])` on your configuration

**Comment by 20Tauri** [comment]
Tests done on 3118... Cannot reproduced (using default configuration and my own)

I've made a fix based on the stack trace (I now force `ruler[0]` to `int`)
If you want, you can try again to use the plugin.
I'm curious on the result on `view.settings().get("rulers", [])` on your configuration

**Comment by aymaluser** [comment]
I think that did the trick.  Seems to be working fine, now.  Thanks for the quick turnaround.  I think this plug-in will be very useful.  I'll buy a license, even, if it turns out to be so :)
