### ISSUE TITLE
Add a status indicator for the build command

### ISSUE THREAD

**Issue by aymaluser** [20Tauri/DoxyDoxygen#55]
Please add a status indicator for the build command.  Currently, on Linux, when you build documentation for a large project, the sublime text UI just freezes until the build is complete.  It would be nice if at some point you could not do the build on the main UI thread, and/or add a status indicator of some kind such that the user at least knows why the sublime UI has frozen and that it's only temporary.

**Comment by 20Tauri** [comment]
Good suggestion.
This will also allow continue working while documentation generation...
Will be implemented in next release (probably on tuesday on Evolution branch)

**Comment by 20Tauri** [comment]
Added in 0.47.0... Available in regular version too

**Comment by aymaluser** [comment]
I like it, thanks :)
