### ISSUE TITLE
Handling ES6 exports

### ISSUE THREAD

**Issue by ondreian** [20Tauri/DoxyDoxygen#56]
I've been using DoxyDoxygen for a week or so now, and using `export` seems to cause some trouble for the autofill feature.

here is the example output of a function with and without using `export`

```
/**
 * { function_description }
 *
 * @param      {<type>}  a       { parameter_description }
 * @param      {<type>}  b       { parameter_description }
 * @return     {<type>}  { description_of_the_return_value }
 */
function sum ( a, b ) {
  return a + b
}

/**
 * { item_description }
 */
export function sum ( a, b ) {
  return a + b
}
```

**Comment by 20Tauri** [comment]
Thank for reporting... This keyword will be correctly supported in next release (in few hour on evolution channel)

A partial fix (no type guessing) may also be done adding this setting

```
        {
            "languages":  [ "js" ],
            "parsers":    [ "LanguageJavaScript, "LanguageGeneric"" ],
            "doc_styles": [ "JsDoc", "GoogleClosure" ]
        },
```

**Comment by ondreian** [comment]
Thanks.

**Comment by 20Tauri** [comment]
Now released on all channels
