### ISSUE TITLE
Alt + Q seems to be splitting every word onto a comment line

### ISSUE THREAD

**Issue by aymaluser** [20Tauri/DoxyDoxygen#57]
Whenever I use Alt + Q or the update command on an existing comment block, all the words in the @brief or other descriptive multi-word fields are getting slip or tokenized onto new lines.  Please fix asap.

So, it looks something like this:

/// @brief 
///             This is the main entrypoint.

Becomes this after Alt + Q:

///
/// @brief
///             This
///             is
///             the
///             main
///             entrypoint.

**Comment by aymaluser** [comment]
Whenever I use Alt + Q or the Update command on an existing comment block, all the words in the @brief or other descriptive multi-word field are getting split or tokenized onto new lines. Please fix asap.

So, it looks something like this:

/// @brief
/// This is the main entry point.

Becomes this after Alt + Q:

///
/// @brief
/// This
/// is
/// the
/// main
/// entry point.

**Comment by aymaluser** [comment]
I noticed that it seems to wrap according to the current cursor position, which could be a feature.  However, it's really not clear how to use that effectively.  It seems more like a workaround than a feature at this point.  FYI, I'm coding in C++ and using Doxygen style.  There is a note in the settings about Doxygen that I think might be related, but I'm not sure.

```
// .. note::
//     There is no DoxyDoxygen parameter to set the preferred line length.
```

**Comment by 20Tauri** [comment]
Thank for reporting

This is strange... I cannot reproduce. Please check your setting
- sublime text 'rulers' settings (first value should be >= 80)
- doxydoxygen `max_line_reducing` settings

If seem correct, the best is probably to also send a fully report (right click, "doxydoxygen report"->"anomaly report", then add a short description and right click, and click "send")

**Comment by 20Tauri** [comment]
This look like a configuration error...
If someone else if affected or if you have further information please ask.

**Comment by aymaluser** [comment]
Setting the ruler seems to have resolved the issue.  Thanks.

**Comment by 20Tauri** [comment]
Sound like #54 ...
I don't understand why, but your 'rulers' settings before fix seem to be a list where the first item is a float.
And this float has probably a low value

Before your fix, I still wonder what was the result on view.settings().get("rulers", []).
To get it, select menu "view->show console", then "view.settings().get("rulers", [])"

Usually this value is "[]" using default... Including 3118

Thanks

**Comment by aymaluser** [comment]
Default:

> > > view.settings().get("rulers",[])
> > > [-0.1, 0.2]

Set to 80 in the user settings file:

> > > view.settings().get("rulers",[])
> > > [80, -0.1, 0.2]

**Comment by aymaluser** [comment]
This settings should allow you to reproduce the problem:
"rulers": [0,0,80],

Then, add an extra long @brief description.  Hit cntrl+q.  If it repros, all the words will get wrapped to their own lines.

**Comment by aymaluser** [comment]
More Information:
- It seems to be wrapping according to the first rulers column setting.  If this true, I don't know, maybe this is by design?  So, if I change to this, then it wraps at the 80 column, which is the desired behaviour.  I'm happy with this design.  I don't think you should change anything.  

"rulers": [80,0,0],

**Comment by 20Tauri** [comment]
Thanks,

You're right, the value used is the first value of `rulers`. This is explain on [customization page](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php), setting `max_line_reducing`

This value is also used by the wrap command include in sublime text.
According [Unoffical Doc](http://docs.sublimetext.info/en/latest/reference/settings.html) is strange to have floating and negative value here...

Sounds like a bug in Sublime.
I will add a security in next release... Value < 1 will be ignored.

Thanks

**Comment by aymaluser** [comment]
I think it may have to do with another plug-in I have called CursorRuler.  I realize now that they use floating point and negative values.  They must be using the built-in column lines/rulers to draw their lines.

**Comment by aymaluser** [comment]
So, I think maybe what's happening is that with that plug-in, you get an unexpected default rulers settings.  Since I didn't set it, for your plug-in, the expected wrap is 80 (according to your documentation).  However, in my case, due to the CursorRuler plugin, I had a default setting that is not obvious / that I didn't know about.  They must be using the rulers settings internally to implement their plugin.  Make sense?

**Comment by 20Tauri** [comment]
Yes, that explain the problem...
I'm affected by the seem problem as Sublime Text integrated wrap command (see https://github.com/icylace/CursorRuler/issues/3 for details)

Instead of contacting the author, I will change me way on querying "rulers"

```
sublime.load_settings("Preferences.sublime-settings").get("rulers", [])
```

The following line should do the job... It's will be great if you can confirm... This plugin seem hard to remove (https://github.com/icylace/CursorRuler/issues/7), so I will not try to install it.

For now, your best option is to set `rulers` to [80]... This approach may also prevent problem using this plugin with others plugin
