### ISSUE TITLE
Allow to use its own symbols

### ISSUE THREAD

**Issue by ncoden** [20Tauri/DoxyDoxygen#6]
Allow (with configuration files for exemple) to use our own comment symbols

For exemple : `/**`, `**` and `*/` to have the following comment.

```
/**
** Comment
**
** ...
*/
```

Some schools or organisations (as the 42 school where I am) have a norm for C programming and comments

**Comment by 20Tauri** [comment]
This will be added in next release.
Thanks for suggestion

In your configuration file, you will have to set

``` json
    "prefered_comments_styles": [
        [
            "/**",
            "**"
        ],
```

**Comment by ncoden** [comment]
:+1: Thanks
