### ISSUE TITLE
Problem when using the PHP final keyword

### ISSUE THREAD

**Issue by g4z** [20Tauri/DoxyDoxygen#60]
There seems to be an issue with the docblock generation when using the PHP "final" keyword.

Example of DoxyDoxygen without the final keyword (works OK)

``` php
class A {
    /**
     * { function_description }
     *
     * @param      <type>  $a      { parameter_description }
     * @param      <type>  $b      { parameter_description }
     * @param      array   $c      { parameter_description }
     *
     * @return     array   ( description_of_the_return_value )
     */
    public static function X($a, $b, array $c) {
        return $c;
    }
}
```

Example of DoxyDoc with the final keyword (does not work)

``` php
class A {
    /**
     * { item_description }
     */
    final public static function X($a, $b, array $c) {
        return $c;
    }
}
```

Also, note that it seems that the position of the 'final' keyword is not too important, so the following is also valid PHP...

``` php
class A {
    public static final function X($a, $b, array $c) {
        return $c;
    }
}
```

**Comment by 20Tauri** [comment]
Thank a lot for this report,

DoxyDoxygen uses his own grammar for PHP and "final" was not correctly handled.
I have fix it and now I use your example in my tests suite.

Fixed version is release in both "DoxyDoxygen (evolution)" and "DoxyDoxygen"
