### ISSUE TITLE
Problem when using the PHP abstract keyword

### ISSUE THREAD

**Issue by g4z** [20Tauri/DoxyDoxygen#61]
It seems that a similar problem to that described in issue #60 also occurs with with PHP 'abstract' keyword.

For example, using 'Alt-q' to generate documentation for things marked abstract does not work...

``` php
abstract class A {
    abstract function B(array $a);
}
```

If i remove the abstract keywords, everything (Alt-q docblock generation) works fine...

``` php
/**
 * Class for a.
 */
class A {

    /**
     * { function_description }
     *
     * @param array $a { parameter_description }
     */
    function B(array $a) {}
}
```

**Comment by 20Tauri** [comment]
Thank a lot for this report,

DoxyDoxygen uses his own grammar for PHP and "abstract" was not correctly handled.
I have fix it and now I use your example in my tests suite.

Fixed version is release in both "DoxyDoxygen (evolution)" and "DoxyDoxygen"
