### ISSUE TITLE
Not detecting template parameter name

### ISSUE THREAD

**Issue by sadovsf** [20Tauri/DoxyDoxygen#62]
When you have template parameter expecting template class it's name is not parsed:

``` c++
template<template<class> class __type>
class MyTemplateClass { ... }
```

Such template definition is used so you can send templated type inside like so:

``` c++
template<class>
struct MyStructure { ... }

MyTemplateClass <MyStructure> instance;
```

Off course you have to specify template parameter for MyStructure inside MyTemplateClass. Currently this generates documentation with <unnamed> instead of __type when documenting MyTemplateClass.

**Comment by sadovsf** [comment]
btw. Thank you for such great plugin :) keep up great work :)

**Comment by 20Tauri** [comment]
Thank for reporting and using this software.

It's an advanced usage : "Template template parameter" is part of c++17  :) .
I have improved template support in 0.52.0 (released on all channels).
Your example is now supported.

Regards,

**Comment by sadovsf** [comment]
It definitely is :)
Thank you! Will give it a test once it updates on https://packagecontrol.io/packages/DoxyDoxygen ;-)

**Comment by sadovsf** [comment]
Looks like it is working well now. Thank you! :)
