### ISSUE TITLE
Color settings

### ISSUE THREAD

**Issue by 1walaky** [20Tauri/DoxyDoxygen#64]
Hello!
How can I set the @param, @var and  @return color to simple grey, just any other comment texts?
Thank you!

**Comment by 20Tauri** [comment]
Hello,
Coloration is handled by theme (.stTheme files) according syntax (tmLanguage or sublime-syntax files).

Here an [example of sublime-syntax](https://github.com/sublimehq/Packages/blob/master/Java/JavaDoc.sublime-syntax) (you can see the `meta.documentation.tag prefix` and `keyword.other.documentation.return.javadoc` for example)

tmTheme file simply make the binding between them

``` xml
            <key>name</key>
            <string>Keyword</string>
            <key>scope</key>
            <string>keyword - (source.c keyword.operator | source.c++ keyword.operator | source.objc keyword.operator | source.objc++ keyword.operator), keyword.operator.word</string>
            <key>settings</key>
            <dict>
                <key>foreground</key>
                <string>#F92672</string>
            </dict>
```

DoxyDoxygen neither "fix" them (hard to maintain) nor add any specific listener to have his own coloration (time consuming)... So the best is currently to fix them be your own.
    - unzip  `Color Scheme - Default.sublime-package`
    - edit tmTheme file adding a specifc scope for `keyword.other.documentation` (to have a specific  color) or simply "- keyword.other.documentation" in the matching rule

**Comment by 1walaky** [comment]
Ok! Thank you very much!!!

**Comment by 20Tauri** [comment]
I don't understand why you close then reopened this issue.
Do you expect more support regarding this plugin ?

**Comment by 20Tauri** [comment]
Without more explanations I prefer to close it for readability
