### ISSUE TITLE
@todo + TAB Seems To Be Broken

### ISSUE THREAD

**Issue by aymaluser** [20Tauri/DoxyDoxygen#65]
On Sublime Build 3124 from the beta channel:

Steps to reproduce the problem:
Type:
// @todo
And hit the TAB key.

On my machine, the @todo tag disappears.

**Comment by 20Tauri** [comment]
Confirmed... and unfortunately it's not version dependent...
A fix has just been released on all channels

Thank for reporting

**Comment by 20Tauri** [comment]
Released in 0.55.2
