### ISSUE TITLE
Doxydoxygen attempting to complete #!/bin/bash

### ISSUE THREAD

**Issue by fgimian** [20Tauri/DoxyDoxygen#67]
Straight forward problem:
1. Create a new file and set syntax highlighting to be Shell Script (Bash)
2. Type `#!/bin/bash` on line one and hit Enter
3. Result

``` bash
#!/bin/bash
##
```

Might want to rethink the trigger for that one 😄

**Comment by 20Tauri** [comment]
Hi again,

Have you read the doc ? 
You can set "continuation_on_last_comment": to `false` or press <kbd>Shift</kbd>+<kbd>Return</kbd> to modify the behaviour.

Can appear as a strange default chose but really powerful....

**Comment by fgimian** [comment]
Thanks so much, sorry I'll go through the docs properly shortly.

Cheers
Fotis
