### ISSUE TITLE
Show doxygen on hover?

### ISSUE THREAD

**Issue by moof2k** [20Tauri/DoxyDoxygen#69]
One feature I miss from Visual Studio / Visual AssistX is the [QuickInfo viewer](http://docs.wholetomato.com/default.asp?W206), where it displays the doxygen for a given symbol when you hover the mouse over it.

SublimeText 3 now exposes an [on_hover](http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener) callback when the mouse hovers over a location for a short time.. I was wondering if your plugin stores parsed doxygen in a format usable for this purpose?

**Comment by 20Tauri** [comment]
Not yet...

I also not sure to manage my own indexation is a good approach...
Sublime Text as his own (ex: window.lookup_symbol_in_open_files)
As multiple indexations is time consuming. The best approach is probably to hook the existing one, then parse the file (if needed) to extract the documentation block.

In pratice, those Sublime Text functions are really efficient, but poor on C++
C++ often use alternative indexation (CLang based) for example...
Find the best compromise (performance vs reliability) is not so easy to find.

An extra feature may be to generate snippets for functions...
It's nearly the seem job

**Comment by moof2k** [comment]
Good ideas, thanks for responding!

I later stumbled upon this presentation on [parsing doxygen comments using clang](http://llvm.org/devmtg/2012-11/Gribenko_CommentParsing.pdf), and an associated [clang-complete fork](https://github.com/gribozavr/clang_complete) that implements it. I wonder if its possible to separately adapt this to fire in response to an on_hover..

Closing this ticket as it's not super relevant to your plugin.

**Comment by asheeshr** [comment]
For anyone that may come across this in the future, you can accomplish this by using the EasyClangComplete package and enabling show_type_info. It picks up the doxygen style comments that you can generate with this plugin and shows them in a tool-tip.

**Comment by 20Tauri** [comment]
Thanks you, I will add your suggestion in both the changelog and the FAQ for the next release.
