### ISSUE TITLE
Ability to have newlines in the header

### ISSUE THREAD

**Issue by kauinoa** [20Tauri/DoxyDoxygen#72]
Perhaps there is a way to do this already and I just don't know how to do it.

"preferred_comments_styles": [
        [
            ["//", "-", ""], 
            "///",
            ["//", "-", ""],
        ],
    ],

This generates:
//-----------------------------------------------------------------------------------------------------------------
/// @brief      Does something
///
/// @return     Returns something
//-----------------------------------------------------------------------------------------------------------------
bool foo();

But what I am looking for is:
//-----------------------------------------------------------------------------------------------------------------
///
/// @brief      Does something
///
/// @return     Returns something
///
//-----------------------------------------------------------------------------------------------------------------
bool foo();

The ability to have new lines in the comments. Is this already possible?

**Comment by 20Tauri** [comment]
You can use
```
        [
            [ "///", "-", "\n///" ],
            [ "/// ", ],
            [ "///\n///", "-", "" ],
        ],
```

Unfortunately versions prior to 0.56.1 (just release on Evolution branch) cannot reparse this advanced settings.

**Comment by 20Tauri** [comment]
Now released in all branches
