### ISSUE TITLE
Problem in tab

### ISSUE THREAD

**Issue by heiwais25** [20Tauri/DoxyDoxygen#74]
Hello, I'm happy to use this doxydoxygen package in sublimetext.

What I have problem in using doxyoxygen is if I type "@return" and tab, then @ disappear.. other command was similar. How could I fix this??

Thank you.

**Comment by 20Tauri** [comment]
Hello,

I cannot reproduce this problem on my version 0.57 (with Doxygen DocStyle)

Please first update the plugin (don't care if you're in 0.56).
Snippets are dynamically generated (EventListener->on_query_completions).
Some issues have been fixed.
The only known problem is with "@code{}" like name.

If the problem persist, it's may be useful to give more context... SublimeText version used, language used, settings.... The simplest way is to get them is probably to use integrated agent.
Once the problem occur, right click in your sublime text view, then select "DoxyDoxygen Report -> Anomaly Report" to list them. Add a comment and right click to sent them (or copy/paste them here)

Regards,
