### ISSUE TITLE
alt+Q at the line template <typename T> will pop up doxygen comments for previous function

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#75]
I am using the newest doxydoxygen evolution.

Here is an example to reproduce the problem

``````
class Foo
{
  void PrintSomething();

  template <typename T>
  bool Hi();
};
``````

If my cursor is at the line `template <typename T>` it will pop up doxygen comments for `void PrintSomething();`

If my cursor is at the line `bool Hi();` it will pop up the correct doxygen comments though.

Do you agree that it should pop up the right doxygen comments at the line `template <typename T>`?

**Comment by 20Tauri** [comment]
It's not a change but the way DoxyDoxygen find the "nearest" function.
Only function name matter.
Using defaults, 1 line down is like 3 lines up. So 2 lines up is "nearest" than 1 line down

To have the wanted behavior update the following setting from 3 to 1
```json
    "distance_for_bottom_line_over_top_line": 1,
```
But consider this case before
```c
void function1(
    int param1,
    int param2,
    int param3,
    int param4,
) // cursor HERE will match to second function
{
}

void function2()
```

**Comment by jasjuang** [comment]
Thanks for the great explanation
