### ISSUE TITLE
typedef struct not recognize as struct

### ISSUE THREAD

**Issue by nicolasaujoux** [20Tauri/DoxyDoxygen#78]
Hello,

I am trying to customize DoxyDoxygen to generate specific Doxygen tags for my C code.
While everything works fine for functions, I have some problems to generate Doxygen for structs, defines, enums.
I tried to add a block_layout and it works, for an enum when I type "/** + enter" but not with the "alt+q". It is not very convenient but I can work with that. 
However, code like that : 
`typedef enum blabla
{
}
`
is not recognize with the following context 
`
 "context": [{ "key": "kind",      "operator": "equal",          "operand": "enum" },
`
Is there a solution to make it work ?

Thank you,
Nicolas

**Comment by 20Tauri** [comment]
Hello,

There's no relation between `block_layout` settings and your problem

<kbd>Alt</kbd>+<kbd>Q</kbd> detects some entities based on sublime text grammar.
To make it work there are 2 two issues
- first, on current SublimeText version, "typedef enum blabla {} typedef_name;" will not recognize "blabla" as an "entity.name.enum" (no coloration). If you remove the typedef "enum blabla {};", this will work. It's a bug in grammar. Check the last [Sublime Text Grammars](https://github.com/sublimehq/Packages/tree/master/C%2B%2B), if the bug still exist, open an issue on this project
- second, in DoxyDoxygen. Even with the currently right supported syntax "enum blabla {};". DoxyDoxygen doesn't handle "entity.name.enum". In most languages, "entity.name.class" is recognize" and "enum" is class introducer like the c++ "enum class"... But, I will add this in a next release...

Regards,
