### ISSUE TITLE
Updating JSDoc with optional param removes square brackets

### ISSUE THREAD

**Issue by brenwell** [20Tauri/DoxyDoxygen#80]
Hey there,

I am having an issue the when i press `alt+cmd+Q` to update the skeleton structure of my JSDoc comment block it removes the [] brackets from around any optional params

**Before**

```js
/**
 * Does something
 * 
 * @param  {object}    point
 * @param  {number=}   x        The x coordinate
 * @param  {number}   [y]       The y coordinate
 * @param  {number}   [z=0]     The z coordinate
 */
function setPointCoordinate(point,x,y,z=0)
{
    if (y !== undefined) point.x = x;
    if (y !== undefined) point.y = y;
    if (z !== undefined) point.z = z;
}
```

**After**

```js
/**
 * Does something
 *
 * @param  {object}   point  The point
 * @param  {number=}  x      The x coordinate
 * @param  {<type>}   y      { parameter_description }
 * @param  {number}   z      { parameter_description }
 * @param  {number}  [y]    The y coordinate
 * @param  {number}  [z=0]  The z coordinate
 */
function setPointCoordinate(point,x,y,z=0)
{
    if (y !== undefined) point.x = x;
    if (y !== undefined) point.y = y;
    if (z !== undefined) point.z = z;
}
```
It works with the Google Closure optional format {number=} but not with the JSDoc format which becomes quite messed up. Which can be found here http://usejsdoc.org/tags-param.html.

**User Settings**

```js
// Settings in here override those in "${packages}/DocBlockr_with_update_capability/Doxy.sublime-settings",
// and are overridden in turn by syntax-specific settings.
{
    "preferred_tabs_sizes": [ 8, 3, 3, 3, 3, 3 ],
}
```

Perhaps I am doing something wrong

**Comment by 20Tauri** [comment]
Thank for reporting,

"[x]" is currently considered as the parameter name. It's an issue (but not so easy to fix).
I will fix it in a next release

**Comment by brenwell** [comment]
That's great. I will keep an eye out.

**Comment by BITespresso** [comment]
Any chance to get this fixed in the foreseeable future? I'd like to document an optional parameter with a default value and there is no other way than:

```js
/**
 * @param  {number}   [z=0]     The z coordinate
 */
```

**Comment by 20Tauri** [comment]
Unfortunatly, it's not easy to fix (and JSDoc specific).
Probably not in a near future.

**Comment by BITespresso** [comment]
Thanks for your answer!

**Comment by 20Tauri** [comment]
I finally chose to fix this bug... cause is a long term one & very annoying for JS users.
This has requiere a lot of changes and it's only available in the evolution branch (https://github.com/20Tauri/DoxyDoxygen/releases/tag/0.69.3)

**Comment by BITespresso** [comment]
I'll try it out.
