### ISSUE TITLE
ability to switch between doc_styles?

### ISSUE THREAD

**Issue by grahamannett** [20Tauri/DoxyDoxygen#83]
hey, 
I was curious if its possible to switch between supported doc_styles for instance between apidocs and and JsDoc.

for instance my settings are 
```
{
    "debug_enabled": true,
    "profiles": [
        {
            "languages":  [ "js" ],
            "parsers":    [ "LanguageJavaScript" ],
            "doc_styles": ["JsDoc", "ApiDoc"], // or "YuiDoc", "DoxyDoc", Doxygen", "ApiDoc"... according your preference
        },
    ]
}
```

I would like to normally use jsdoc but occasianlly need to use apidoc.  I realize i can get the api doc per line stuff by @, ctrl+ [space] but was interested in switching completely between jsdoc and apidoc similar to how switching comment style would work.  unfortunately using the switch comment style just changes from something like:

```
/**
 * { function_description }
 *
 * @param      {<type>}  argument  The argument
 */
function asdf(argument) {
  // body...
}
```

to 

```
/*-------------------------------------------------------------------------*//**
 * { function_description }
 *
 * @param      {<type>}  argument  The argument
 */
function asdf(argument) {
  // body...
}
```

am i missing a command (read the docs but didnt seem to find anything that worked) or is this not possible?  otherwise what does doc_styles entail?

**Comment by 20Tauri** [comment]
You've answered your question

The first item of the "doc_styles" list is used to generate "docblockr"
The others ones are currently only used to populate the completion list

There is no way to generate several "docblockr" styles for a same "language"... and I'm not sure redefine a "language" with the same parser is a good option for you
