### ISSUE TITLE
Comments for members inside blocks

### ISSUE THREAD

**Issue by asheeshr** [20Tauri/DoxyDoxygen#84]
I am using DoxyDoxygen for adding C style comments for block members. Is there a way to get single line comments for members of functions/structs in the Doxygen style?

```
struct a {
    type member1; /**< Comment */
    type member2; /**< Comment */
}
```

**Comment by 20Tauri** [comment]
Not really a question about this plugin, but Yes. Doxygen support `///<` (single ligne and command on the right of members

**Comment by asheeshr** [comment]
My question was to how to get the plugin to add single line comments? Alt + Q only enables the function comment block. I looked at the config file but it wasn't obvious how to enable a shortcut to the single line comment.

**Comment by 20Tauri** [comment]
There's currently no way to add a comment line for each field of a structure. 
As generated comment will be "poor" (only based on name), not sure there's a high value...
Will NOT be planned in a near future.

Maybe multi cursors or a regexp may be an alternative

**Comment by asheeshr** [comment]
It would be helpful if there was a shortcut to at least generate the comment delimiters i.e. Ctrl + D generates `/**< */` for struct members.

**Comment by 20Tauri** [comment]
Try something like that in your settings
```
    {
        "keys": ["ctrl+d"],
        "command": "insert_snippet",
        "args": {
            "contents": "/**< ${1:default comment} */"
        }
    },

```
