### ISSUE TITLE
How to use command style \brief instead of @brief ?

### ISSUE THREAD

**Issue by bblanchon** [20Tauri/DoxyDoxygen#85]
Hi @20Tauri,

I'm working on a C++ project with the following convention:

```c++
/*!
 * \brief Bla bla bla
 * \param value Bla bla
 */
```

I didn't manage to make the `\brief` syntax work.
I tried to make my own DocStyle from the [HeaderDoc example](https://github.com/20Tauri/DoxyDoxygen_contrib_HeaderDoc), but I lost the ability to auto-fill the brief.

Can you help me use the `\brief` syntax?

Regards,
Benoit

**Comment by 20Tauri** [comment]
Hi Benoit,

Sounds simple. Have you try `doxygen_command_prefix` setting ?
Please refer to the [user manual](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php#settings-references) for detail

Regards,

**Comment by bblanchon** [comment]
I cannot believed I missed this! 🙄 
Thanks !
