### ISSUE TITLE
Cmd+Enter and Cmd+Shift+Enter not adding * at the beginning of the line

### ISSUE THREAD

**Issue by bblanchon** [20Tauri/DoxyDoxygen#86]
Hello Sebastien,

When editing a comment, I expect Cmd+Enter (which inserts a line below the current line) and Cmd+Shift+Enter (which inserts a line above the current line) to behave as the Enter key does, which is to automatically insert a * at the beginning of the line to preserve the block layout.

Regards,
Benoit

**Comment by 20Tauri** [comment]
Hello Benoit,

Looks like a good enhancement.
It's simply a new key binding to add and the [doxy_chain_commands](http://20tauri.free.fr/DoxyDoxygen/v2/page_faq.php#can-i-call-doxydoxygen-from-the-command-line) command to use

Here the key binding to add (will be included in defaults settings in the next release)

```json
    {
        "keys": ["ctrl+enter"],
        "command": "doxy_chain_commands",
        "args": {
            "commands": [
                [ "view.move_to", {"to": "hardeol", "extend": false} ],
                [ "view.doxy_enter" ],
            ]
        }
    },
    {
        "keys": ["ctrl+shift+enter"],
        "command": "doxy_chain_commands",
        "args": {
            "commands": [
                [ "view.move_to", {"to": "hardbol", "extend": false} ],
                [ "view.move", {"by": "characters", "forward": false} ],
                [ "view.doxy_enter" ],
            ]
        }
    },
```

This evolution has been released in version 0.60.0 (evolution).
Key bindings per platform is detailled in [the documentation](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php#key-bindings)

Regards,

**Comment by bblanchon** [comment]
Hi Sebastien,

I just received the update via Package Control.
The new shortcuts are working as expected :+1:

Thank you very much.
Benoit

**Comment by deathaxe** [comment]
😞  I always used <kbd>Ctrl+Enter</kbd> to finalize comment editing and add a new line to start coding. I need to move the cursor to the next line manually if it already exists or need to delete the added `#` (in python) to start coding. It's a bit annoying.

So how can I efficiently finalize comment editing and add a new source code line after the comment?

**Comment by 20Tauri** [comment]
According the [documentation of `continuation_on_last_comment` ](http://20tauri.free.fr/DoxyDoxygen/v2/page_customization.php#settings-references) the suggested shortcut is <kbd>Shift</kbd>+<kbd>Enter</kbd>. 

Of course, Sublime Text allow you to redefine your own. Simply copy the default key bindeys in your preferences file. Should be something like that:
```json
	{ "keys": ["enter"], "command": "insert", "args": {"characters": "\n"} },
```

**Comment by deathaxe** [comment]
👍 Works fine. 

Had another keybinding for <kbd>Shift</kbd>+<kbd>Enter</kbd>. Therefore didn't realize this feature. 

Thanks
