### ISSUE TITLE
Question: how to set max space

### ISSUE THREAD

**Issue by lockz** [20Tauri/DoxyDoxygen#87]
When use  "php_generate_fully_qualified_name": true and long names i'm getting this
![_01](https://user-images.githubusercontent.com/5790762/28651399-abb66aac-72bc-11e7-808a-1f7a3648d25e.jpg)

Can i get this result?
![_02](https://user-images.githubusercontent.com/5790762/28651420-c561e7c4-72bc-11e7-8cfb-fb7be33045ff.jpg)

**Comment by 20Tauri** [comment]
Nice example !
It's not specific to `php_generate_fully_qualified_name` but more like `preferred_tabs_sizes` work.
`tabs_size` are rebuild globally and without limit.

It's a possible enhancement:. consider them as group (blank line as seperator) or add a maximum differnece from the `preferred_tabs_sizes` setting

**Comment by lockz** [comment]
Can you provide config example. I'm don't understand what i should do.

**Comment by 20Tauri** [comment]
Sorry, in short: it's currently not possible

You can try "`preferred_tabs_sizes": [ 0 ]` take will disable tabs handling.

I plan to add a new settings in the future to group tabs_size computation by "blank separated items" AND/OR another one to avoid be to far from "preferred_tabs_sizes" (that is currently more a minimum)

**Comment by 20Tauri** [comment]
A new parameter has just been added
Please update to .061.0, than change `group_tabs_sizes_by` setting to `section`
