### ISSUE TITLE
Wrongly parsing PHP codes?

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#88]
Environment: ST 3143 Stable Portable. Only Package Control and DoxyDoxygen are installed.

There is an extra `)|` in the doc.

![gif](https://user-images.githubusercontent.com/6594915/30512297-d485ec0c-9b1e-11e7-9640-36a18b65ed80.gif)

source before: 
```php
<?php


function isDiff (string $old, int $new) {
    if ($old === $new) {
        return false;
    }

    return true;
}
```

source after: 
```php
<?php

/**
 * Determines if difference.
 *
 * @param      string     $old    The old
 * @param      )|integer  $new    The new
 *
 * @return     boolean    True if difference, False otherwise.
 */
function isDiff (string $old, int $new) {
    if ($old === $new) {
        return false;
    }

    return true;
}
```

**Comment by 20Tauri** [comment]
Thank for reporting.
I confirm a problem in the php parser (the variable "new" was confused with the operator).
The fix will be deployed next week

Regards

**Comment by 20Tauri** [comment]
Fix applied
