### ISSUE TITLE
Wrongly parsing PHP return type declarations

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#89]
Environment: ST 3143 Stable Portable. Only Package Control and DoxyDoxygen are installed.

The return type should be `string|null` (i.e., `?string`).
The function `nop_1` seems to play a role in this error as well.

**before**:
```php
<?php

class foo
{

    public function nop_0(string $str): ?string
    {
        return $str;
    }

    public function nop_1(string $str, callable $func): string
    {
        return $func($str);
    }

}
```

**after**:
```php
<?php

class foo
{

    /**
     * { function_description }
     *
     * @param      string           $str    The string
     *
     * @return     Function|string  ( description_of_the_return_value )
     */
    public function nop_0(string $str):? string
    {
        return $str;
    }

    public function nop_1(string $str, callable $func): string
    {
        return $func($str);
    }

}
```

**Comment by 20Tauri** [comment]
Thanks again. This will improve this software

DoxyDoxygen was not handle PHP 7 return type... So, this break the parsing.
A basic fix has been done and will be deployed this week

I've find a clear syntax definition. For example, on [php.net](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration), I discover the following syntax:
```php
function ret_nullable() ?int {
    if (...) {
        return 123;
    } else {
        return null; // MUST!
    }
}
```

**Comment by 20Tauri** [comment]
Fix applied on "evolution" branch

**Comment by 20Tauri** [comment]
Fixed on main version too
