### ISSUE TITLE
Use the current identation

### ISSUE THREAD

**Issue by ncoden** [20Tauri/DoxyDoxygen#9]
Try to detect the current indentation, and adapt the documentation to it.
For exemple :

```
/**
** @brief                   It's one (long) function
** ...                      ...
*/
static inline unsigned char one_function(void);

/**
** @brief                   It's an another (short) function
** ...                      ...
*/
void                        an_another_function(void);
```

Or (with a min of 4 tabs)

```
/**

** @brief           A very short function
** ...              ...
*/
void    one_short_function(void);
```

**Comment by 20Tauri** [comment]
DoxyDoxygen purpose is documentation, not code...
Indentation is detected "in comment" using "Super+Shit+Right" on OS/X
But you can write your own plugin that set dynamicly the DoxyDoxygen settings, key "prefered_tabs_sizes"
