### ISSUE TITLE
Do not "continuation_on_last_comment" for one-line only comments

### ISSUE THREAD

**Issue by beletsky** [20Tauri/DoxyDoxygen#93]

**Comment by beletsky** [comment]
I often run into a bothering issue.

I write a one-line comment using //, then press Enter at the line end going to write the line of code next, but I get comment continuation instead.

I know I can press Shift-Enter to get the plain line. But I found it strange while coding that Enter key behavior differs at plain code lines and at one-line comment lines. At the same time, when the caret is inside a multi-line comment, I surely expect Enter key to add a new comment line.

I think it will be great if there'll be a setting for disabling comment continuation for one-line only comments. So if I would want to get a block of one-line comments, I need to begin a comment with // only twice - one for the first line, and the other for the second to indicate I want multi-line block.

**Comment by 20Tauri** [comment]
Thanks for reporting

Sound like a bug... But, I cannot reproduce.
Here two examples with and without 'continuation_on_last_comment' activated

```c

int foo()
{
    return 1; // I press enter here with 'continuation_on_last_comment' == true
              // 
}

int foo()
{
    return 1; // I press enter here with 'continuation_on_last_comment' == false
    
}

```

Can you give me a detailled example (language used, minimal code example, version used...) ?
"Preferences->DoxyDoxygen->Contact->Anomalies Report" may help you to generate it

Regards

**Comment by beletsky** [comment]
I'm so sorry I've misled you. It's surely not a bug, the option works right as expected. It's an enhancement I want to have.

For the case 'continuation_on_last_comment' == true, it'll be great to have another option like 'continuation_on_last_comment_oneline', which have to control if next comment line will be added for one-line comments only.

That is, with 'continuation_on_last_comment_oneline' == true, do all the same as now it is. But with 'continuation_on_last_comment_oneline' == false when the Enter is pressed at the end of one-line comment, then skip adding second comment line, but add plain code line instead.

This option is of great importance for the coding style like this:

```
// The next line declares a variable.
int i;

// Increase it.
++i;
```
Hope now I explain myself right.

Regards.

**Comment by 20Tauri** [comment]
`continuation_on_last_comment` only affect single line comment...
So should already work as you expect `continuation_on_last_comment_oneline` will work

```c
{
    // The next line declares a variable..<PRESS ENTER HERE => No continuation to produce your example you have to type "int i;">
    int i;

    // Increase it.<PRESS ENTER HERE => No continuation>
    ++i;
}
```

You have read the documentation and try the option... So I think this not work for you

**Comment by beletsky** [comment]
I have "continuation_on_last_comment": true in my configuration because it's really useful. Now I type:

```
// Comment<PRESS ENTER => next line is commented, so I need to backspace it or press Shift-Enter instead.
int i;
```

I want it to be:

```
// One-line comment<PRESS ENTER => Next line is a plain one, I can write code immediately.
int i;

// Long comment first line.<PRESS ENTER => Next line is a plain one, I have to enter '//' once more.
// Second line.<PRESS ENTER => Next line is commented automatically.
// Third line.<PRESS ENTER => ... and so on.
++i;
```

**Comment by 20Tauri** [comment]
Thanks for the explanation,

The plugin currently don't care of the number of single line comments.
Your workflow seem less efficient but more intuitive (may be a good enhancement and a better default behavior)
I will probably make the change in the next version (coming next week in evolution branch).
I will update this issue when done

Regards,

**Comment by 20Tauri** [comment]
Deployed in evolution branch
