### ISSUE TITLE
DoxyDoxygen not recognizing Markdown Table

### ISSUE THREAD

**Issue by smfelsher** [20Tauri/DoxyDoxygen#94]
I am documenting a table in one of my function header comments using Markdown. When I press `Alt-Q`, the Markdown formatting is destroyed. Is there any way to configure DoxyDoxygen to ignore a Markdown table?

```
Header1 | Header2
------- | -------
Item 1  | Value 1
Item 2  | Value 2 
```

**Comment by 20Tauri** [comment]
Thank you for reporting

[Markdown Extra](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html#markdown_extra) are part of Doxygen but not yet supported by DoxyDoxygen

Not a really good alternative but on current version you can use something like "@code TABLE_HERE @endcode" to prevent rewrap. In the next release, I will prevent rewrap on lines starting with | to "solve" this issue

This will add partial support of table
```markdown
| Right | Center | Left  |
| ----: | :----: | :---- |
| 10    | 10     | 10    |
| 1000  | 1000   | 1000  |
```

**Comment by smfelsher** [comment]
Very good. Thank you for your support.
