### ISSUE TITLE
Ability to have documentation insert after function header

### ISSUE THREAD

**Issue by grahamannett** [20Tauri/DoxyDoxygen#96]
I saw https://github.com/20Tauri/DoxyDoxygen/issues/92 and believe its basically the same issue.  Python standards seem to always have the comments past the header of the class/function but I cant find any setting or way to get this to work.  I know https://github.com/KristoforMaynard/SublimeAutoDocstring this project does it (and is what I am using in the meantime) but seems like it would be very possible to add a way for users to select where the comment block is inserted.

**Comment by 20Tauri** [comment]
In [Doxygen Manual](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#pythonblocks), there's an example of documentation using comments (but I agree, it's unusual in python code... and few python developper use Doxygen)

As written in #92  , docstring are supported... The only current restriction is on creation.
Of course, it's possible to add an option (the main difficulty is to detect the insertion point)...
I will consider this in a future release... It that sense especially for Sphinx-like users

**Comment by grahamannett** [comment]
Hmm, seems like it would be trivial to add the insertion into area after the header depending on language? but I have no idea since its not open source.  That would be a really appreciated feature.  
Also I cant really get the example custom doc style to work either, following the instruction in the other repo, it "works" but i get this at the top
`'*********** This plugin format is no longer supported ***********' `

**Comment by 20Tauri** [comment]
Oups, I forget to push the example with the new format (seels that nobody use this feature !)
It's now fixed

**Comment by 20Tauri** [comment]
The lastest release (0.63.0) now include this feature.
This is NOT the default. Because Doxygen with docstring is really poor.
To activate it, edit "preferred_comments_styles" (add docstring block before python comment block). Default configuration contain the lines (commented)

**Comment by grahamannett** [comment]
Just saw this! Awesome seems to work.  Thanks for the plugin!

**Comment by ffflabs** [comment]
I guess I'm doing something wrong. I uncommented those lines, so my config looks like

```
    "preferred_comments_styles": [
        [
            "/**",
            " *"
        ],
        [
            ["/*", "-", "*//**"], // <=> /*-------------------*//**
            " *"
        ],
        [
            ["//", "-"], // <=> //------------------------
            "///"
        ],
        // [
        //     [ "//", "/", "" ],
        //     [ "//", "/", " ", " ", "/", "//" ],
        //     [ "", "/", "//" ]
        // ],
        [
            "\"\"\"", // Python docString
            "",
            "\"\"\""
        ],
        [
            "##",
            "##"
        ],
        [
            ["#", "-"], // <=> #-------------------------
            "##"
        ]
    ],
```

However, if I have a class, say:

```python
class Something(Resource):
    def get(self):
        return 1
```

Pressing `ALT + Q` over it results in:

```python
class Something(
    """
@brief Class for something.
"""Resource):
    def get(self):
        return 1
```

**Comment by 20Tauri** [comment]
No, everything ok on your side... It's a bug in python Parsing.
I just fix it in all branches

**Comment by grahamannett** [comment]
Hah wow @20Tauri you are the greatest.  I had noticed this a few days ago as well and just figured it was settings I had and made a bad workaround that somewhat mitigated this issue in my user Doxy sublime settings.  but this actually how it would work.

Off topic but really curious are you interested in porting something like this to VSCode?  I love this package and have been a long time sublime user and understand the need to charge but I would really love to use this in VSCode and know many others would find this incredibly useful as well.  If it's out of the question then no problem, but I would be ecstatic to help you if necessary.
