### ISSUE TITLE
Parsing error with the combination of dll macros, vector of vector and const

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#97]
Here is a minimal code to reproduce the problem

```
namespace abc
{
class MyClass
{
 public:

  WINDOWS_DLL
  MyClass();

  WINDOWS_DLL
  std::vector<std::vector<MyData>> MyFunc(const std::vector<MyData> &data);

 private:
  std::vector<std::vector<MyData>> MyPrivateFunc(
      const std::vector<MyData> &data);
};

}  
```

If I move the cursor to the constructor and type alt+Q, it will throw an exception and ask me to send a report. I already did actually but I want to report more of my findings.

If I remove the dll macros for both functions. It works like usual. If I remove the const in one of the functions, it also works like usual. If I change the return type from vector of vector to int it also works like usual. If I change MyData to int it also works like usual. I feel like I am hitting an edge case here. Still would be nice to see this fixed!

**Comment by 20Tauri** [comment]
Thanks for this detailed description

I've received your Crash Report and analyzed it.
The fix has been publish in evolution branch... May take a short while until Package Control detect it.
But, it's fixed.

Due to ">>" (c++11) the should be considered as "> >" and not the shift operator

**Comment by jasjuang** [comment]
Thanks, it is working now!
