### ISSUE TITLE
[C++] Unable to generate doxygen comments for destructor with DLL macros

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#98]
Here is a minimal example

```
namespace abc
{
class MyClass
{
 public:

  WINDOWS_DLL MyClass();

  WINDOWS_DLL ~MyClass();
};

}  
```

If I put my cursor at the line of where the destructor is and then type alt+Q, the template description of the constructor shows up instead of the destructor. If I remove the dll macros and type alt+Q, the template description shows up for the destructor correctly.

**Comment by 20Tauri** [comment]
Try thsi, on destructor, to understand
```
>>> view.scope_name(view.sel()[0].begin())
'source.c++ meta.namespace.c++ meta.block.c++ meta.class.c++ meta.block.c++ meta.function-call.c++ variable.function.c++ '
```

It's a bug in the C++ grammar that come with Sublime Text.
This is not detected as an entity (a destructor), but as a function call
New grammars have introduce improvements, but also regressions. Your example works fine with Sublime Text 3084

I will add this "known issues" on this [dedicated page](http://20tauri.free.fr/DoxyDoxygen/v2/page_known_issues.php)

You can try to update your grammar from [Sublime Text Git](https://github.com/sublimehq)
But you probably has to fix it yourself or/and contact the sublime text team to fix it

**Comment by 20Tauri** [comment]
Documentation updated

**Comment by jasjuang** [comment]
Thanks for the explanation. I will file an issue with sublime.
