### ISSUE TITLE
ALT + Q on SQL files

### ISSUE THREAD

**Issue by ffflabs** [20Tauri/DoxyDoxygen#99]
In my preferences I have

```json
{
    "languages":  ["sql" ],
    "parsers":    [ "LanguageGeneric" ],
    "doc_styles": ["Doxygen"], // "DoxyDoxygen_contrib_HeaderDoc" (if installed for Objective C)
     "preferred_comments_styles": [
                [
                    "/**",
                    " *"
                ]
            ]
        },
```
However, when pressing ALT + Q over a function:

```sql
CREATE OR REPLACE FUNCTION get_page(page_id bigint) 
```

It adds `##` as comment style:

```sql
##
## @brief { function_description }
##
## @return { description_of_the_return_value }
##
CREATE OR REPLACE FUNCTION get_page(page_id bigint) 
```

Which isn't a valid comment in SQL, and therefore it's highlighted as a syntax error by the linter.

(Anyway, I couldn't get any documentation tool to parse javadoc style comments either, so this wouldn't have worked, anyway)

**Comment by 20Tauri** [comment]
Will be fix in next release
This affect the SQL that come with SublimeText (others aren't affected)

This works from now
```json
    "preferred_comments_styles": [
                   [
                       "--!",
                       "--!"
                   ]
               ],

```

**Comment by ffflabs** [comment]
If I type `--!` and then ALT+Q it does generate that kind of comments... if I press ALT+Q on an empty line before function declaration, it still uses `##`.

I wonder if Doxygen can parse that kind of comments anyway.

**Comment by 20Tauri** [comment]
`--!` should work even with previous version
SQL comment style have been fixed in the last version (regular and evolution)
Should be available soon in Package Control

**Comment by ffflabs** [comment]
I've added the following to my Doxy.sublime-settings (User)

```json
{
            "languages": ["plpgsql", "PL/SQL", "SQL", "plsql", "sql"],
            "parsers": ["LanguageGeneric"],
            "doc_styles": ["Doxygen"], // "DoxyDoxygen_contrib_HeaderDoc" (if installed for Objective C)
            "preferred_comments_styles": [
                [
                    "--!",
                    "--!"
                ]
            ]
        }
```
But now, instead of `##` I get `/**` comment style. Still better imho. Anyway, as I said Doxygen cannot parse SQL files. I've tried using [sql2doxygen](https://github.com/chrisoldwood/sql2doxygen) but it's very limited

**Comment by 20Tauri** [comment]
Strange, works fine for me with default SQL syntax.
In your example, the languages field looks strange. The correct value is given by `view.scope_name(0)` (use the word after `source.`
